### ISSUE TITLE
Suggestion: add SkipTrailingRows to the CreateLoadJobOptions Big Query API 

### ISSUE THREAD

**Issue by ssgtcookie** [GoogleCloudPlatform/google-cloud-dotnet#1177]
It's already possible to skip the first X lines when uploading a .csv file like so:
```
CreateLoadJobOptions options = new CreateLoadJobOptions
{
    SkipLeadingRows = 11
};
```

Unfortunately there isnt a function that does the opposite thing: remove lines at the bottom of a file .csv file. Such an option can come handy because some .csv files do have a summary or copyright message at the end of the .csv file. This copyright message might result in unwanted import results in Big Query when using the uploadCsv function. Suggestion:
```
CreateLoadJobOptions options = new CreateLoadJobOptions
{
    SkipTrailingRows = 2
};
```

The work "trailing" can be anything as long as it's clear that it skips the last lines of the .csv file.

**Comment by jskeet** [comment]
The .NET client library is really just a wrapper around the BigQuery API - rather than performing this on the client side, I think it would be better for this to be part of the API itself (then exposed as options), and it's not at the moment.

@jcondit may know a suitable place to request this feature.

**Comment by jskeet** [comment]
I've filed a feature request internally; I'm going to close this one now as we won't be doing anything within this repo unless/until the API starts to support it.
