### ISSUE TITLE
Make coverage filtering handle the Spanner case

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#1321]
We want the Spanner.Data integration tests to contribute to coverage of Spanner.V1.
This could be an extra bit of configuration, or just include all dependencies for production APIs.

**Comment by jskeet** [comment]
Thinking about it, this is going to be a pain when we've gone GA for Spanner - when Spanner.Data depends not on a project reference but a *package* reference, we won't have the source code any more for the version we're testing against... and the integration tests *won't* be testing the new version of Spanner.V1, whatever that contains.

@benwulfe: Any thoughts about this? Fundamentally I think we may well to make sure we have a "good enough" set of integration tests in each project in isolation.

**Comment by benwulfe** [comment]
I think one fundamental issue here is that we havent spent the necessary
cycles thinking about what the proper API surface would be for someone
targeting Spanner.V1 because the potential customer size is so small.

If we did, we'd come up with proper integration tests for those scenarios
Until that happens, we are left with whatever Spanner.Data is dependent on.

The related issue of not running tests on V1 x+1 when we release
Spanner.Data is part of the overall issue affecting our test matrix.

Possibly if we consider the general problem of 'what happens when you have
a test that verifies functionality between GCP A and GCP B when they are
package dependencies'.  In that case, maybe the right thing to do is to
have the test declared/maintained in one place, but run both whenever A or
B is released.  We could do this in code via a shared lib and stub tests in
each -- or keep the test in either A or B and do some tooling.  Tooling
could be declarative (file config, assembly attributes) or even assembly
manifest inspection.  We could inspect the resulting test assembly manifest
for all of its dependencies and run the integration test if we are
releasing any of them.
Of course this or the declarative version would make test discovery a PITA.

**Comment by benwulfe** [comment]
Also, while its very possible for us to write new integration tests that
capture the dependency between A and B, that approach is not only much more
work, but also more prone to fail as it can easily get out of sync from
what the contract between A and B actually is.

**Comment by jskeet** [comment]
Yes, we can definitely test (say) Google.Spanner.Data when a new version of Google.Spanner.V1 is released. Chasing the backwards dependency shouldn't be hard to do given apis.json.

For right now, I think we're probably fine to just add any *project* dependencies into the test filter... so we get to see what the integration tests are doing for Spanner right now. Then when we get more deeply into multi-version testing, we can make sure we bear coverage in mind at that point.
