### ISSUE TITLE
Can't add Google.Cloud.Storage NuGet package

### ISSUE THREAD

**Issue by uluhonolulu** [GoogleCloudPlatform/google-cloud-dotnet#1393]
The latest stable version of Google.Cloud.Storage (2.0.0) requires Google.Api.Gax (≥ 2.1.0-beta02), which can't be resolved (I assume it's not a stable version). I'm not against using betas, but I guess the Storage package should be marked as Prerelease if it depends on a prerelease version, no?

**Comment by jskeet** [comment]
This definitely shouldn't be the case. I'd expect that:

- Google.Cloud.Storage 2.0.0 should depend on Google.Api.Gax 2.0.0
- Google.Cloud.Storage 2.1.0-alpha02 should depend on Google.Api.Gax-beta02

Investigating.

**Comment by jskeet** [comment]
Just checked, and that's what NuGet says as well:

Storage 2.0.0: https://www.nuget.org/packages/Google.Cloud.Storage.V1/2.0.0
Storage 2.1.0-alpha02: https://www.nuget.org/packages/Google.Cloud.Storage.V1/2.1.0-alpha02

Note that 2.0.0 was released a long time before Google.Api.Gax 2.1.0-beta02, so I wouldn't expect it to be *feasible* for it to refer to that.

Presumably you've reported this because you received a build failure - could you give more details of how you got into this situation? That'll make it easier to understand what's going on.

**Comment by uluhonolulu** [comment]
I installed the prerelease version first, but then I started getting some strange results on my Website which I wasn't getting from my tests, so I figured it might be a different version of some assembly. My tests were using Google.Api.Gax.Grpc 2.0.0, so I decided to revert everything to this. 

Looking closer into this, I think the problem is not the dependency itself, but rather something in the installation script. Here's the console output.

![cloudapi](https://user-images.githubusercontent.com/872764/29518927-0f331d0c-8684-11e7-9575-9fd43efcb7eb.png)

This is a 4.5 project.

**Comment by jskeet** [comment]
There isn't an installation script within the package.

My guess is that there are still traces of the prerelease in your project - are you able to reproduce this with a clean project? Can you give details of the project itself, e.g. which version of .NET you're targeting, and which version of VS etc you're using?

**Comment by uluhonolulu** [comment]
Tried to add it to a different project, and it worked just fine. I guess you're right. Closing, and sorry for the trouble.
