### ISSUE TITLE
Nuget's "Project Site" link points back to github page.  Maybe should link to docs.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#1399]
For example, look at:
https://www.nuget.org/packages/Google.Cloud.Speech.V1/1.0.0-beta12
I click on the "Project Site" link and get taken to this github repo, which is useful, but still many clicks away from telling me what the speech API does and how to use it.
Would one of the following links better serve users?
https://cloud.google.com/speech/
https://cloud.google.com/speech/docs/

**Comment by jskeet** [comment]
It depends on what the user wants to do - if they're following the link to report an issue, the github link is more useful.

Another alternative would be the .NET-specific API docs: https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Speech.V1/index.html

Let's talk about this with the Product team.

**Comment by jskeet** [comment]
cc @omaray

**Comment by omaray** [comment]
Given that the Nuget package is about Speech, then part of me feels that clicking on the "Project Site" should send to a "speech specific" concept indeed.

And again, given that the Nuget package is about C# of course, then clicking on "Project Site" should be a project about C# too.

So the current GitHub link is "okay" since users can find the Speech specific info by scrolling down - and of course it's a C# repo, hence that checkbox is checked.

Sending to the Client Library Reference is also pretty good but only since there is a landing page! Sometimes library references are just that... a set of methods/functions/parameters. So I could go with that since there is a nice landing.

Sending directly however to the Speech Docs on cloud.google.com might be a bit too generic for a user who is looking at C# specifically. Also, the client library ref documentation has a link to the Cloud Site docs at the very top, which is nice as well to address that concern.

My 2 cents, but I don't feel super strongly one way or another and I'm happy to let Dev Rel and the C# team decide.

**Comment by jskeet** [comment]
@SurferJeffAtGoogle: Any additional thoughts on this? It's still not clear to me what the best solution is.

**Comment by jskeet** [comment]
Closing for now having added this to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/BACKLOG.md)

**Comment by SurferJeffAtGoogle** [comment]
Now that I've had more experienced clicking through other projects' nuget links, I think that linking to the github repo is totally appropriate.  And the README has links to all the product docs.

**Comment by jskeet** [comment]
Great, thanks - will remove it from the backlog doc.
