### ISSUE TITLE
Unnecessary storage bucket name in request body metadata

### ISSUE THREAD

**Issue by EatonZ** [GoogleCloudPlatform/google-cloud-dotnet#1418]
The bucket name is not needed in the request body metadata since it is already specified in the URI.

![gcs_dupe](https://user-images.githubusercontent.com/3020941/29898644-e411fed0-8db4-11e7-9ad1-1955274cc7b4.PNG)

**Comment by jskeet** [comment]
An example of the code you're using here would be helpful - at first glance I thought you were creating a bucket.

The code creating the body has been like this from day 1, so I'll have to experiment to see whether it's actually required or not.

I'm going to mark this as a P2 as I can't see that there's a great deal of harm being done (it's only adding a fairly small amount of data to be transmitted) but I'll see what I can do for a future release.

**Comment by EatonZ** [comment]
It's uploading a file, here's some sample code:

```
var storageClient = StorageClient.CreateAsync().Result;
using (var fileStream = File.OpenRead("file.txt"))
{
    var uploadedObject = storageClient.UploadObjectAsync("sample-bucket", "file.txt", "application/octet-stream", fileStream).Result;
}
```

**Comment by jskeet** [comment]
Yup, I worked that out after a few minutes of going in the wrong direction :)

**Comment by jskeet** [comment]
This is actually pretty fiddly to fix, because of the way we delegate - if you just pass in an `Object` to `UploadObject`, that *does* have to have a bucket specified... so the overload that takes the bucket and object names separately just delegates to the overload that takes an object, creating a destination object.

I think I'd *prefer* not to make the code more complicated for the very minimal benefit in not including the bucket name here - do you have any concerns other than "neatness" here?

**Comment by EatonZ** [comment]
It was just an optimization to remove an unnecessary, duplicated value.
I always try to make my network requests as tiny as possible.

I wouldn't worry about it if it will introduce complex code changes. It's just something I wanted to bring up if it was simple as a 1 line fix.

**Comment by jskeet** [comment]
SGTM. I very much doubt that it'll ever cause an extra packet :)
