### ISSUE TITLE
StorageClient.ListObjects should default to an empty prefix

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/google-cloud-dotnet#142]
otherwise I'm typing 'client.ListObjects(bucketName, "")' all the time.

**Comment by jskeet** [comment]
We discussed this before in #17 - back when it was an overload instead of just a parameter with a default. The vague consensus there was that listing objects in a bucket with no prefix was a rare situation. Certainly happy to reconsider - and as the prefix is the last non-optional parameter, we definitely *can* make it optional.

Possibly talk to the team to see what proportion of `ListObjects` calls don't specify a prefix?

**Comment by csells** [comment]
There’s value in decreasing the number of concepts that need to be considered as people ramp up. By making the prefix non-default, you require everyone calling ListObjects to understand what a prefix is and why they might need one and what to pass when then don’t care just they’re just trying to make something work. The use of a prefix is for optimization.

**Comment by jskeet** [comment]
Hmm. I agree it's an optimization in that you could apply the filtering client-side, but I think it's probably one that it's worth making people aware of right from the start. (While I like to make things simple, I'm also in favour of highlighting things that users really *should* be thinking about from the start. See Noda Time for plenty of examples of that...) I'm not convinced either way yet. (Once we've agreed the right thing to do, the implementation is obviously trivial.)

**Comment by iantalarico** [comment]
Just to chime in and ping the old thread. I am with csells.  I think an optional parameter would be the best of both worlds.  We can have a prefix param but also not require the user to pass in an empty string.

**Comment by jskeet** [comment]
@ivannaranjo and @chrsmith - in issue #17 you both requested this be mandatory (at least, Chris's "yes" may have been about that, or may have been about the delimiter). Any strong feelings against me making this optional?

(I'm assuming it's still worth having as a method parameter rather than putting it in ListObjectsOptions, which is *relatively* unwieldy.)

**Comment by jskeet** [comment]
Ping @ivannaranjo and @chrsmith for feedback...

**Comment by chrsmith** [comment]
I do not have strong opinions, but have a slight preference for requiring you to specify the prefix. But ultimately, if this bug report is a proxy for end-user feedback we should make the fix if doing so is trivial. So I'd push for having an overload without the parameter, even if don't like the idea in principle.

As for why I'd rather have the API force you to specify a prefix, using "" to mean "get everything" and "/images" to just get things in the "/images" pseudo-folder makes sense. Having three different overloads (no-prefix, with-prefix, and with ListOptions object) seems like overkill.

Moreover, IMHO we don't want to make the API too initiative and like a file system -- e.g. like the `File` and `Directory` BCL types -- because GCS is _not_ a file system. It is a storage API with a very specialized set of constraints. Like Jon said, getting users to internalize that up front is in their best interest in the long-run.

But nuances aside, in this situation there is no underlying complexity/runtime argument. It is just about removing a parameter in the situation where it is not needed. (When you don't care what the filter is or don't want to provide one.)

**Comment by jskeet** [comment]
@Capstan Do you have any opinion on this from a Storage team perspective? Do we want to always make clients think and be explicit when they're listing objects (because listing all objects is relatively rare) or is listing all objects within the bucket such a common operation that we should avoid clients having to be explicit about it?

**Comment by Capstan** [comment]
IMO, it should default to an empty prefix. I think of it as a filter and filters as being optional.

**Comment by jskeet** [comment]
Righto, will do - thanks for the feedback.
