### ISSUE TITLE
Users want faster cloud storage uploads.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#1480]
I compared the performance of our current cloud storage library to gsutil.  Source code is here:
https://github.com/SurferJeffAtGoogle/scratch/tree/master/StorageSpeed

Uploading 1 GB file:
```
rennie@rennie:~/gitrepos/scratch/StorageSpeed$ dotnet run newfile bigone.bin -g 1
rennie@rennie:~/gitrepos/scratch/StorageSpeed$ ls -sh
total 954M
954M bigone.bin  4.0K bin  4.0K obj  4.0K Program.cs  4.0K StorageSpeed.csproj
rennie@rennie:~/gitrepos/scratch/StorageSpeed$ time dotnet run upload bigone.bin bookshelf-dotnet.appspot.com

real    0m35.922s
user    0m6.176s
sys     0m6.428s
rennie@rennie:~/gitrepos/scratch/StorageSpeed$ time gsutil cp bigone.bin gs://bookshelf-dotnet.appspot.com/bigone2.bin
Copying file://bigone.bin [Content-Type=application/octet-stream]...
==> NOTE: You are uploading one or more large file(s), which would run
significantly faster if you enable parallel composite uploads. This
feature can be enabled by editing the
"parallel_composite_upload_threshold" value in your .boto
configuration file. However, note that if you do this large files will
be uploaded as `composite objects
<https://cloud.google.com/storage/docs/composite-objects>`_,which
means that any user who downloads such objects will need to have a
compiled crcmod installed (see "gsutil help crcmod"). This is because
without a compiled crcmod, computing checksums on composite objects is
so slow that gsutil disables downloads of composite objects.

/ [1 files][953.7 MiB/953.7 MiB]   70.5 MiB/s
Operation completed over 1 objects/953.7 MiB.

real    0m13.647s
user    0m5.068s
sys     0m2.472s
rennie@rennie:~/gitrepos/scratch/StorageSpeed$ gsutil ls -lh gs://bookshelf-dotnet.appspot.com/bigone*
953.67 MiB  2017-09-20T19:07:57Z  gs://bookshelf-dotnet.appspot.com/bigone.bin
953.67 MiB  2017-09-20T19:08:48Z  gs://bookshelf-dotnet.appspot.com/bigone2.bin
TOTAL: 2 objects, 2000000000 bytes (1.86 GiB)
rennie@rennie:~/gitrepos/scratch/StorageSpeed$
```

**Comment by benwulfe** [comment]
I took a quick look at source and it seems the chunk size might be a bit small:

https://github.com/google/google-api-dotnet-client/blob/b26fd3effa79808c229d5bf8814777ecc90a7193/Src/Support/Google.Apis/Upload/ResumableUpload.cs#L730

which looks to be 4k?  In our testing in Firebase Storage, chunk size had an outsize effect on upload speed and we implemented dynamic chunking in all the clients which had a significant improvement on upload times.  What you do in dynamic chunking is exponentially increase the chunk size with every subsequent chunk until you see a network error  -- at which point you fall back to a smaller size.

I do not believe you need to revert to parallel uploads in the library to fix this.  You should be able to get closer to 6s.

**Comment by jskeet** [comment]
Looking at this, the 4K is the size for *reading* from the client's stream, rather than being the upload. Our minimum upload chunk size is 256K, and the default is 10MB. I wouldn't expect the local read size to make that much difference in many cases, although increasing it a bit probably wouldn't hurt. More research needed to work out where the time is going here.

**Comment by jskeet** [comment]
Hmm... I've just uploaded 1GB from my box (at home) and it took 9 minutes with both the library and gsutil. Investigating further - it could be that it's sensitive to the version of .NET being used.

**Comment by jskeet** [comment]
@SurferJeffAtGoogle: Can you let me know the details of the environment you ran your test from?

I'm uploading 1GB in about 25s at the moment from within GCP with the client library. The gsutil upload timing varies a lot - between 9s and 31s; it's typically around 16s.

**Comment by jskeet** [comment]
More information, testing with a 1GB file, upload only:

- From home, I can easily saturate the network (10Mbps up) with both gsutil and .NET
- From work on wifi, I get ~110Mbps up with .NET and ~80Mbps with gsutil (oddly)
- From work on ethernet, I get ~180Mbps up with .NET and ~240Mbps with gsutil

I'll try again from a GCP machine.

**Comment by jskeet** [comment]
On GCP (on Linux) I'm getting about 800Mbps upload from gsutil, but only ~200Mbps from .NET.

**Comment by jskeet** [comment]
cc @chrisdunelm 

Okay, I've made a lot more progress on this.

I believe gsutil is getting faster uploads here mostly due to reading from the disk in parallel to issuing network requests - and possibly reading the file more efficiently too. The .NET code reads a chunk from the upload stream, then sends a request, then reads another chunk, sends the next request, etc. We could in theory be reading the next chunk from disk while uploading the previous chunk. (This will require more memory, however, as we'd have two chunks in memory at a time instead of 1.)

There are IO limits on GCP, usually related to the size of the disk. I found that by using a 500GB disk instead of a 50GB disk, I improved throughput from ~200Mbps to 320Mbps. Removing the file access entirely (using a "fake" stream that simply returned a number of bytes read without doing any more work) achieved around 600Mbps.

Increasing the internal buffer size used to copy data - currently via reflection - improved that 320Mbps to 390Mbps. That's still less than the 800Mbps from gsutil, of course, but it's not *too* shabby,

Any changes to this would have to be in the REST support library, potentially:

- Allowing the buffer size to be user-specified
- Allowing concurrent read and upload

The first doesn't get us as much benefit, but is very simple to do. The latter is a bit more involved - and I haven't proved the benefit yet. Doing so will be a bit trickier to test, but I'll see what I can do. I think we'd want to make it opt-in anyway, given the memory differences. (It will probably involve reading using ReadAsync instead of Read, too, which is probably a good thing but could throw up issues.)

**Comment by jskeet** [comment]
It's more complicated, it turns out.

My fake stream uploaded all 0s rather than random data - and if I do the same with a file, it hits ~500Mbps, showing that the data itself affects things.

I've added timing for "waiting to read data" vs "waiting to upload data" and most of the time *is* taken by the upload. I've created a prototype of "concurrent read/write" and that doesn't seem to have a significant impact on the speed.

I still don't know how gsutil is doing this so fast...

**Comment by jskeet** [comment]
Okay, so I *still* don't quite know what gsutil is doing, but we can improve things in some cases, at least.

Factors that are known to affect the .NET performance on GCE:

- Size of disk, which affects available IOPS
- Whether the content is compressible or not
- Whether the library reads concurrently or not

Test have shown that changing the buffer size while reading data *doesn't* make much difference - especially true when reading concurrently.

On a GCE instance with a small disk, concurrent reads can double the speed, so that's worth doing.

The change will be in the REST support library. I've filed https://github.com/google/google-api-dotnet-client/issues/1123 to cover this.

**Comment by jskeet** [comment]
Very reluctantly, I'm going to close this as infeasible. I've looked at changing `ResumableUpload` to implement concurrent read and write - and it would be *extremely* hairy to get right in a robust way. There would be a lot of corner cases with a stream read failing concurrently with an HTTP upload failing etc.

Within a single tool like gsutil, it's easier to constrain how the code is used and recover from specific errors - within a library, there are a lot more opportunities for things to go wrong.

**Comment by frankyn** [comment]
Hey @jskeet I found this while doing research for Python. Did you account for gsutil uploading the entire file without chunking? As it has a condition for uploading the entire [file when the size is known](https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/gcs_json_api.py#L1286), otherwise it uses a [100 MB default chunk size](https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/utils/boto_util.py#L193).

**Comment by jskeet** [comment]
@frankyn: That's good to know, thanks. We have special-casing for when the file size is known, but it still uses chunks... partly to make retries work better.
