### ISSUE TITLE
Question: Is there an ETA for Firestore?

### ISSUE THREAD

**Issue by Sohojoe** [GoogleCloudPlatform/google-cloud-dotnet#1606]
I see the Firestore API is in active development; is there an ETA or roadmap?

**Comment by jskeet** [comment]
I don't have an ETA as such - obviously we won't end up with GA libraries until after the API itself is GA, so that's potentially a way off.

I'm talking with the Firestore team about a few more tweaks to make before we create and publish an alpha package - I'd hope that would happen some time in November, if that's any use to you. Once it's out, we'd *really* love any feedback you might have.

**Comment by Sohojoe** [comment]
Great - I will keep an eye out for the alpha
