### ISSUE TITLE
Firestore: Support for real-time updates 

### ISSUE THREAD

**Issue by pauloevpr** [GoogleCloudPlatform/google-cloud-dotnet#1618]
Is there any roadmap to add support for real-time updates?

**Comment by jskeet** [comment]
I don't know - I believe the expectation is that that's more of a mobile concern, whereas the current API is expected to be used server-side.

**Comment by pauloevpr** [comment]
Thank you very much for your reply. I get your point, but there are some use cases where real-time support would be extremely useful, even on the server-side. For example, when:

- Integrating with custom server applications (in scenarios where Cloud Functions can't handle the business logic)
- Integrating with web services such as Asp.Net and Asp.Net Core
- Implementing client libraries for platforms which are not currently officially supported by Google, such as Xamarin, WPF, UWP and Windows Forms

Without real-time support, the API seems incomplete, especially because [Firestore's RPC documentation](https://firebase.google.com/docs/reference/rpc/google.firestore.v1beta1?authuser=0) does mention support for real-time updates through the [Listen](https://firebase.google.com/docs/reference/rpc/google.firestore.v1beta1?authuser=0#google.firestore.v1beta1.Firestore.Listen) function of the service interface.

**Comment by jskeet** [comment]
I'll pass your comment back to the team - I'm only doing the C# API for it, following the direction given by the main Firestore team.

**Comment by pauloevpr** [comment]
Thank you very much. I appreciate your help.

**Comment by schmidt-sebastian** [comment]
Hi, Sebastian here from the Firestore client team. We are currently offering realtime support in the mobile clients for the Web, iOS, Android. We also launched the Node Server SDK with realtime support. 

Since we are currently offering Firestore Server SDKs for Node, Go, Python & Java (with C# and others in the works), we first wanted to gauge what the demand for realtime support for these server languages was. Our users have since indicated that they do want to see realtime support in all of these languages, and hence we are treating this as a high priority item on our immediate roadmap. While I can't provide a timeline, expect to see realtime support across all of our SDKs in the not so distant future.

**Comment by pauloevpr** [comment]
Great news! Thank you very much for your feedback.

**Comment by jskeet** [comment]
Will leave this issue open as a placeholder to indicate that we're intending to do it. I'll mark it as P2+, but that just means it's not *imminent* (i.e. working to get it in the next release). It doesn't mean it's not important :)

**Comment by Thaina** [comment]
Nearly end of the year and still no support for C# while all the admin SDK got update last week

And not even a roadmap was solid

**Comment by jskeet** [comment]
No support for this specific API call yet, no. We'll get there, but we're doing lots of other work too.

**Comment by recyclethis** [comment]
From a server side perspective this would be very useful for integrating data collected by mobile devices into line of business systems. 

I take it the heavy lifting for this is in the protocol, and there does not exist yet anything in Google.Cloud.Firestore.V1Beta1 to support this? If support is in V1Beta1 it should be fairly trivial to add an `onSnapshot` method to `QuerySnapshot`.

**Comment by jskeet** [comment]
It's far from trivial to provide the kind of support we want to provide. We would rather take time and do it properly than rush a shoddy option. You can use the client property to get the raw gRPC if you want in the meantime. We will attend this feature request over time, but will resist calls to rush.

**Comment by recyclethis** [comment]
Thanks @jskeet. I'll look at `FirestoreClient.Listen` to achieve this. Maybe I will be able to create extension methods on `QuerySnapshot` and `DocumentSnapshot` until support is officially added. There is a snippet which lays out the groundwork.

**Comment by cleversolutions** [comment]
For anyone else who drops by here, I've played around with Google.Cloud.Firestore.V1Beta1 to create some very basic support for listen. It's not complete, and it's not terribly pretty yet, but it will listen for document and query changes. Checkout the [FirebaseDocumentListener](https://github.com/cleversolutions/FirebaseDotNetRamblings/blob/master/FirebaseDocumentListener.cs) class. Now that the holidays are over, I'm not sure I'll have much more time for it so I'm uploading it as is.

**Comment by schmidt-sebastian** [comment]
Note that there is now also a reference implementation in Java (https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2665)

**Comment by cleversolutions** [comment]
I've updated my [FirebaseDocumentListener](https://github.com/cleversolutions/FirebaseDotNetRamblings/blob/master/FirebaseDocumentListener.cs) to include an extension method for `Query`. Since I'm working outside of `Google.Cloud.Firestore` I've had to use some reflection to access internal methods and properties. You can now use the listener like this:
```
            //Create our database connection
            FirestoreDb db = FirestoreDb.Create(projectId);

            //Create a query
            CollectionReference collection = db.Collection("cities");
            Query qref = collection.Where("Capital", QueryOperator.Equal, true);

            //Listen to realtime updates
            FirebaseDocumentListener listener = qref.AddSnapshotListener();

                       //Listen to document changes
            listener.DocumentChanged += (obj, e) =>
            {
                var city = e.DocumentSnapshot.Deserialize<City>();
                Console.WriteLine(string.Format("City {0} Changed/Added with pop {1}", city.Name, city.Population));
            };

            //Listen to errors
            listener.Error += (obj, e) =>
            {
                Console.WriteLine("Error => " + e.Message);
            };
```

**Comment by ArtificialInsights** [comment]
I just found this thread today - I am working on a large project in Angular and we would like also offer a C# Desktop application for this project. All of my data resides in Firestore. Is their a library yet for Firestore in C#? I saw a mention above for a Google.Cloud.Firestore.V1Beta1. Is this the current library for C#? Is it still in beta? I really don't need real time listening functions in the desktop app, however, it would be a nice feature. 

Thanks in advance

Ronnie

**Comment by jskeet** [comment]
The library you want to use is `Google.Cloud.Firestore` which provides a much higher level abstraction than `Google.Cloud.Firestore.V1Beta1` - but both the library and the underlying API are still in beta.

**Comment by ArtificialInsights** [comment]
OK - Thanks - Yeah, I have been working on this all morning - There are no clear videos or explanations on how to integrate this into a C# project... such as, showing a step by step video on setting up the project in GCP, connecting the Firestore API and setting/Downloading the json file, setting up the environmental variables, etc... so I am in the process of creating such a video... will post shortly... should answer a lot of questions and save new people some time.

**Comment by SimplifyMSP** [comment]
@ArtificialInsights Please know that I'm extremely interested in those videos. I hope that, even if I'm the only one who watches, you'll still be releasing them. 

I've set the authenticate JSON file as an Environment Variable but my application still won't authenticate. I'd appreciate some more granular instructions.

I'm honestly surprised by the lack of C# support from Google. For what it's worth, I don't really need realtime listening either -- but I'd still like to be able to create, modify and delete/remove collections/documents/subcollections from the desktop application.

Thanks!

**Comment by jskeet** [comment]
@SimplifyMSP: You should be able to use Google.Cloud.Firestore from a desktop application. Are there features that you consider to be missing, or is it just the auth issue that you're facing?

**Comment by cleversolutions** [comment]
@jskeet if there is anything I can do to help with this let me know.

**Comment by ShiroYacha** [comment]
I'm working on Xamarin and realtime update is really crutial... +1 for the feature!

**Comment by egortsaryk9** [comment]
+1 for this feature, any updates regarding its state ?

**Comment by jskeet** [comment]
I'm actively working on it. Nothing to show just yet, but it's actively in progress rather than just on my backlog :)

**Comment by jskeet** [comment]
@ShiroYacha: I didn't spot your comment before, but these libraries don't support Xamarin at the moment, so you may have bigger issues than support for this feature.

**Comment by Thaina** [comment]
This is seriously sad that we have android and ios library for firestore but we can't use it on xamarin and unity

If we would have 2 layer of high and low level anyway could we just use it to wrap android/ios native lib in the meantime and switch to low level C# when we ready to implement it

**Comment by schmidt-sebastian** [comment]
@Thaina We are aware of this shortcoming and are aiming to launch full Unity support via the Mobile SDKs in the future. Timeline is still in flux at this point.

**Comment by mikelehen** [comment]
We've also been in contact with Microsoft about the desire for Xamarin bindings. I think there's an Android one available though I haven't tried it yet: https://www.nuget.org/packages/Xamarin.Firebase.Firestore/60.1142.1

I'm not sure what the status is on iOS but I can look into it.

**Comment by Thaina** [comment]
@schmidt-sebastian Couldn't you just opensource it as a raw code and so we could get used to its API for development in the meantime. At least let it work in desktop flow like auth

If it not because the realtime handling mechanism I would already use rest API to work with firestore in unity

**Comment by schmidt-sebastian** [comment]
We cannot share anything publicly yet (this includes both sources and timelines). The C#/Unity API for Realtime Listeners will closely match the existing Android API. You will likely see it fly by in one of @jskeet PRs soon.

**Comment by doczoidberg** [comment]
@cleversolutions unfortunately your code above does not work for me. No events are fired.

**Comment by Thaina** [comment]
@schmidt-sebastian Do we have PR or forked repo I can look up to yet?

**Comment by jskeet** [comment]
Now merged :)

I'll hold off doing a release until the Firestore team have had a look, but then I'll happily do another nuget package.

**Comment by jskeet** [comment]
This is now released in Google.Cloud.Firestore version 1.0.0-beta04.

**Comment by jskeet** [comment]
I've just found a bug for document (not query) watch - it was an easy fix, and I've released 1.0.0-beta05. Apologies for the inconvenience. Separately a) there's no documentation for this feature yet; b) our API doc release process is temporarily broken. I'm hoping to fix both of those soon, but I'm at conferences for a week or so. I'll see how much I can do between talks...

**Comment by nicksav** [comment]
Hi jskeet
I know that this has been closed and you mentioned there will be no docs, but I am trying to get this working in .net core and not sure why it is not firing when I change docs on collection
`
            CollectionReference collection = db.Collection("users");
            Query query = collection.WhereEqualTo("dealerId", 34);

            query.Listen(querySnapshot =>
            {
                string firstName = "";
                string lastName = "";
                foreach (DocumentSnapshot queryResult in querySnapshot.Documents)
                {
                    firstName = queryResult.GetValue<string>("displayName");
                    lastName = queryResult.GetValue<string>("phoneNumber");
                }
            });
`

Is my code Ok?

Thanks
Nick

**Comment by jskeet** [comment]
There are docs that are merged, just not published yet - see https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Firestore/docs/userguide.md and https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Firestore/Google.Cloud.Firestore.Snippets/UserGuideSnippets.cs

I'd expect your listener to fire if there's a dealer with ID 34, yes. I can't test it right now, but I should be able to tomorrow. Currently your listener doesn't do anything with the results - are you just checking whether or not it fires using breakpoints? If you can provide a small but complete example (e.g. as a console app) that would be really helpful. Please file it as a new issue as this is around the feature not working rather than not being provided.

**Comment by nicksav** [comment]
Ok looks like I get this working. Another question, now when we create a listener the first time, it loads the whole collection and after fires when there are some changes. Is there any way to skip the whole loading he first time and just start to listen for changes?

**Comment by schmidt-sebastian** [comment]
The recommended way to do this is to manually track the update time in a field in your Firestore documents. You can then use this field in a query filter when you initialize your snapshot listener.

**Comment by Thaina** [comment]
@schmidt-sebastian And that would break all client update and transaction in every place related to that document. We then need to rebuild our client just to have put another field that already exist and managed by database itself

I was file the request to firestore to query with updateTime for half year and it still have no progress at all. This is also another use case that should put this feature to more priority

**Comment by mikelehen** [comment]
@Thaina Thanks for the feedback.  Unfortunately querying by updateTime is not something we can automatically support because it would require us to maintain a database index sorted by updateTime and that would impose a bottleneck of 500 writes/sec for the collection (See "Maximum write rate to a collection in which documents contain sequential values in an indexed field" from https://firebase.google.com/docs/firestore/quotas).  While this might be okay for some users for some collections, we definitely do not want to impose this limit for all users for all collections.  So for now our recommended solution is to maintain your own indexed field if this is a restriction that works for your use case.

Thanks again for the feedback. Perhaps in the future we could somehow let you opt-into indexing on the internal updateTime on a per-collection basis (with some warnings about the resulting bottleneck). But for now the recommended approach is to maintain your own field.

**Comment by Thaina** [comment]
@mikelehen I don't understand why you maintain index of updateTime field would be slower than us developer need to put another field in every update

And if we really did that, I mean if we have to put our own `CustomUpdateTime = ServerValue.TimeStamp` everywhere we update document, will it _impose a bottleneck of 500 writes/sec for the collection_ ?

If it not then maybe this problem could be solved by your server could just inject hidden `__updateTime__` and `__createTime__` field in every document that get update. It could even have an option for each collection to enable this injection, maybe disabled by default 

This feature actually have so many benefit. Especially to monitoring the format and validate document changed on the live application. I put many reason when I file this request and it really is crucial

And the last but not least
updateTime might cause bottleneck. But I don't see why it would have a problem to expose at least createTime for query? In fact I think createTime should be base order of collection instead of `__name__`

ps. Sorry so have ask these thing on this repo that not directly relate to this problem. But firestore and firebase service don't have its own repo to use for public discussion like this

**Comment by mikelehen** [comment]
Hi @Thaina, you're welcome to ask questions like this on our google group here: https://groups.google.com/forum/#!forum/google-cloud-firestore-discuss

And unfortunately, _yes_, if you put your own `CustomUpdateTime = ServerValue.TimeStamp` everywhere you update documents, that will impose a bottleneck of 500 writes/sec for the collection.  And this is the reason we don't automatically do this.  Same for createTime. If we included it and indexed it, then that would impose a bottleneck of 500 creates/sec.

For high-usage collections you generally don't want to index any sequential field (like a timestamp) because it will cause a "hotspot" (a section of the index that every write needs to access).  Often times you can solve this with a composite index. Rather than just index updateTime, you could index user + updateTime or similar.  Then you'd have a 500 writes/sec/user bottleneck instead of 500 writes/sec for the entire collection.
