### ISSUE TITLE
Support DATASTORE_EMULATOR_HOST and PUBSUB_EMULATOR_HOST environment variables.

### ISSUE THREAD

**Issue by dlorenc** [GoogleCloudPlatform/google-cloud-dotnet#162]
These variables allow client code to talk to local emulators instead of production. See here for how gcloud-goalng supports these:
https://github.com/GoogleCloudPlatform/gcloud-golang/blob/3a8c9824811af5cbfa92a9e976b82fcc3294b73c/datastore/datastore.go#L77

**Comment by jskeet** [comment]
I've started looking at this doing a first pass by hard-coding a change to DatastoreClient.

Observations:

- We need to use insecure credentials for this, so it's not just a matter of specifying a different endpoint
- The snippet-based tests are *slightly* flaky: the first time, one (StructuredQuery) failed; the second and third times, they all passed
- The integration tests show an error: RunQuery_NoResults ends up with a MoreResults of "MoreResultsAfterLimit" instead of "NoMoreResults". The test passes against the real datastore, so this may well be an emulator limitation/bug.

Personally I have a concern about making "use an emulator" the default behaviour if an environment variable is set. That would end up with situations where an emulator is *expected* (for tests), but someone forgot to set the environment variable, and suddenly prod data is impacted. That said, I can certainly see the desire for some code which is designed to run against both prod and the emulator. This is probably something to be discussed across multiple platforms though.

**Comment by chrsmith** [comment]
Before we make any changer to the C# libraries to enable the Datastore emulator, we would also need to be sure whatever method we choose is possible to configure from within the Visual Studio IDE. As it would be unreasonable to expect .NET developers to do the twiddling on the command-line instead of pressing F5.

Since it is just a matter of [environment variables](https://cloud.google.com/datastore/docs/tools/datastore-emulator), I assume we can just set those when you build/run the project locally. (e.g. after you configure the emulator in the IDE).

**Comment by jskeet** [comment]
The "use the emulator that's already running" part is reasonably straightforward from VS, as you can specify environment variables in the properties dialog... although the port will change on each emulator startup. *Starting* the emulator from VS is harder. I'd argue there's benefit in handling the former even if we don't do the latter yet.

**Comment by philipri** [comment]
Does this mean that the DataStore client doesn't work with the emulator at the moment?

**Comment by jskeet** [comment]
@philipri: No, it means that it doesn't *automatically* pick up the emulator from the environment variable.

You can reasonably easily create a `Channel` with insecure credentials based on the environment variable and pass that into the `DatastoreClient.Create` method, and use that `DatastoreClient` in a call to `DatastoreDb.Create`... but none of that is done implicitly.

**Comment by philipri** [comment]
Great thanks @jskeet - the following worked great!

```
            Channel channel = new Channel("localhost", 8174, ChannelCredentials.Insecure);
            DatastoreClient client = DatastoreClient.Create(channel);
            DatastoreDb db = DatastoreDb.Create(projectId, client: client);
```

**Comment by jskeet** [comment]
Dropping the GA milestone here, as there's a bigger discussion around emulator discovery - I don't think everything will be decided before GA, but we'll make it a non-breaking change for 1.1.

**Comment by jskeet** [comment]
Closing for now, pending more general emulator work (which will have a separate tracking issue).

We now have documentation (yet to be posted) in the FAQ about how to use a custom channel.
