### ISSUE TITLE
StorageClient.DownloadObject fails for gzipped data

### ISSUE THREAD

**Issue by Pagonis** [GoogleCloudPlatform/google-cloud-dotnet#1641]
I am downloading statistic reports from my google play developer console using StorageClient

`storageClient.DownloadObject("pubsite_prod_rev_...", objectName, outputFile, null, progress);` and I am getting the error message: 

> Incorrect hash: expected 'CXSlwQ==' (base64), was 'UOn3sg==' (base64)
> at Google.Cloud.Storage.V1.StorageClientImpl.DownloadObjectImpl(String baseUri, Stream destination, DownloadObjectOptions options, IProgress`1 progress)
> at Google.Cloud.Storage.V1.StorageClientImpl.DownloadObject(String bucket, String objectName, Stream destination, DownloadObjectOptions options, IProgress`1 progress)
> at GetGooglePlayData.Program.testAuth() in Program.cs:line 99

The downloaded file is exactly the same as downloaded in gsutil or browser. 
I guess the issue is reconciliation of compressed and decompressed file. Google reports the file is 229B compressed and 978B decompressed. 

The very same issue was already reported by another guy 6 months ago: https://stackoverflow.com/questions/44693652/downloading-from-google-cloud-storage-always-incorrect-hash

**Comment by jskeet** [comment]
Thanks for the report - and for linking to the SO question. I hadn't seen that before.

It's very odd to get that error. I'm at a conference right now, but I'll take a look tomorrow.
If I were to create a build with extra diagnostics, would you be able to try that? (I assume that none of your files are public - basically it's tricky until I can reproduce it.)

**Comment by Pagonis** [comment]
Yes, sure, I can try.
I think the problem is the compressed file (gzip in this case. As I can see). I have tried to download a plain text file and my application works without exceptions.
![image](https://user-images.githubusercontent.com/33512463/32608715-eb10c138-c565-11e7-8181-065f46611e95.png)

**Comment by jskeet** [comment]
Great - I've managed to reproduce the issue now.

I believe the problem is that the .NET library is decompressing the content automatically (due to the Content-Encoding) so it's expecting a hash of the uncompressed text, whereas storage is serving the hash of the compressed data.

Out of interest, were you expecting to get back compressed data or not?

**Comment by jskeet** [comment]
PR #1467 reproduces the issue, but currently I have no workaround. I'm asking internally about how to handle this.

**Comment by Pagonis** [comment]
Thanks for looking into this.
I would like to download compressed, because it will be faster and it will take less Bytes. Anyway, I will decompress them locally.

**Comment by jskeet** [comment]
It would definitely download it in compressed form either way - it's really whether you want to receive compressed or decompressed data in user code. I can see both options being useful, depending on your situation.

I'm digging more deeply into this, and I've found at least two, maybe three problems so far - it's one of those complicated bits with lots of moving parts to consider :(

As a *really hacky* workaround, you could just catch the exception, check that it's for the hash, and then ignore it. The stream will contain all the data at that point anyway. Obviously this is not something you'd want to do for long, but it may help you temporarily.

**Comment by sjkp** [comment]
For what it is worth, the work around I ended up using was just to do
```
var buckets = storageClient.GetBucket(bucketName);
var objects = storageClient.ListObjects(bucketName).ToList();
foreach (var o in objects)
{
  await storageClient.Service.HttpClient.GetAsync(o.MediaLink);
}
```

**Comment by jskeet** [comment]
@sjkp: I'm glad you were able to work around it, but that way you're not validating the hash either - I'd like to get to the stage where we can validate the hash correctly. This area is a bit of a tricky one in terms of there being lots of interlocking concerns, but I'm hoping to make progress.

**Comment by jskeet** [comment]
Okay, I now have a pretty good handle on this, but not necessarily the way forward.

There are three things we need to worry about:

**End result bytes**

If the file is uploaded with a Content-Encoding of gzip, should the data copied into the stream supplied on download be decompressed or not?

My tentative decision here is that it should always be decompressed. If the data should be treated as a gzip blob, then use a Content-Type of application/gzip instead. The Content-Encoding is a more a transport matter - if the Content-Type is application/text, then the downloading user should see text, for example.

**Handling gzipped data when the service has GZipEnabled=false**

If our HttpClient doesn't send an "Accept-Encoding: gzip" header then Google Cloud Storage will automatically decompress the gzipped file and send down the plain text - but the hash is still of the gzipped data.

In this case, there's an additional header: "Warning: 214 UploadServer gunzipped" which we could use to detect this. *We simply cannot validate the hash in this case.*

**Handling gzipped data when the service has GZipEnabled=true*

If our HttpClient sends an "Accept-Encoding: gzip" header then Google Cloud Storage will serve the gzipped data, including a "Content-Encoding: gzip" header. The hash is of the gzipped bytes - the bytes being served - so in theory we can validate the hash. However, the decompression is performed by `HttpClientHandler` which doesn't expose the original data, only the decompressed data. It looks like the handler removes the Content-Encoding and the Content-Length; it's hard (perhaps impossible) to tell the difference between a response that's been decompressed and one that just didn't have a Content-Length at all.

In order to get at the original bytes, we'd need to reimplement decompression ourselves, perhaps in another `DelegatingHandler` in the REST support library. We'd have to then add some way of examining the data as we decompress it, and move the hash validation there instead of in [MediaDownloader](https://github.com/google/google-api-dotnet-client/blob/master/Src/Support/Google.Apis/Download/MediaDownloader.cs) - all in a backward-compatible way, presumably. This is going to be a significant chunk of work.

----

Proposal:

Introduce a new property `DownloadObjectOptions.HashValidation` of type `HashValidationStrategy` (or similar). This would be an enum with values of "Always", "Never" or "WhenAvailable" (naming TBD). "WhenAvailable" would disable hash validation in scenarios where it's infeasible - certainly for the second case above, and potentially (if we can detect it) for the third case until we've got the bigger change in to enable validation properly.

I'm not sure whether the default should be "WhenAvailable" or "Always" - I'm loathe to silently provide invalid data, but equally if the step that *everyone* will take after getting the kind of error reported in this issue is to explicitly use WhenAvailable, then maybe that's better.

I'll look into whether I can detect the third scenario here. If we *always* get a Content-Length for regular content, then maybe WhenAvailable could use the present of the "Warning: 214 [...]" header or the absence of a Content-Length header.

**Comment by jskeet** [comment]
The workaround is now available in 2.1.0-beta01 - if you're downloading a file you know has a Content-Encoding of gzip, you can specify a HashValidationMode of Never in DownloadObjectOptions. I'm still working on a proper fix.

**Comment by jskeet** [comment]
Progress report: the code is in the support library now; when that's next released, I can implement the Google.Cloud.Storage.V1 part.

**Comment by NiceProjects** [comment]
I am trying to download a csv file from my google cloud bucket using Google.Cloud.Storage.V1.StorageClient.DownloadObject(). but getting the exception saying 
An error occurred while sending the request.  I am trying from asp.net mvc application. same working fine when I run in my local IIS under windows 10. when deployed to windows server 2012, getting this error. Error does not giving more details what exactly the issue. any help is much appreciated.

**Comment by jskeet** [comment]
@NiceProjects: Please file a new issue. It doesn't sound like this has anything to do with the original issue.
