### ISSUE TITLE
Authentication error via StorageClient (implicitly)

### ISSUE THREAD

**Issue by hhblaze** [GoogleCloudPlatform/google-cloud-dotnet#1648]
Environment variable is set,
![image](https://user-images.githubusercontent.com/486781/32666739-bb8f44ba-c638-11e7-879d-36b52359356d.png)

I am able to connect and retrieve buckets, if auth.json file is supplied explicitly,
but there is a problem, when authenticating implicitly:

![image](https://user-images.githubusercontent.com/486781/32666903-5852cb96-c639-11e7-8810-259cde39ff53.png)

The other problem when connecting to Datastore, when authenticating implicitly:

![image](https://user-images.githubusercontent.com/486781/32666659-7a55322a-c638-11e7-9852-d4bd6c466b32.png)

Is there a way to connect to datastore supplying credential file explicitly?

Thank you!

**Comment by jskeet** [comment]
These seem to be two potentially-unrelated problems, but unfortunately without very much detail in either of them. Could you open a second issue for Datastore, and keep this one to the Storage issue?

If you could then provide some more details that would be very helpful:

- Am I right in saying you only get the problem when you *don't* have the environment variable set? (Your first sentence sounds like a statement that the environment variable *is* set, but I think you're trying to say "It works when it's set, it doesn't work when it's not.)
- Where are you running the code when it fails? (GAE Flex? GCE? GKE? Somewhere else?)
- Could you give a complete stack trace with any inner exceptions, instead of just showing the type and the message?

(Ditto for the Datastore issue.)

**Comment by hhblaze** [comment]
- I will open second issue for the datastore.
- When connecting to buckets, I can do that when auth.json is set explicitly (StorageClient.Create(credential))
- When connecting to buckets, I can not do that when auth.json is set implicitely (StorageClient.Create()), relying on environment variable.
- When connecting to datastore, I can not do that when auth.json is set implicitely (DatastoreDb.Create()), relying on environment variable.
- I don't know (but want to know) how to connect to datastore explicitly.

**Comment by jskeet** [comment]
Let's leave *all* talk about Datastore out of this issue, to avoid confusion.

How certain are you that your environment variable is actually correct? If you log like this:

```csharp
Console.WriteLine(Environment.GetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS"));
```

what is displayed? What about this:

```csharp
string path = Environment.GetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS");
var fullPath = Path.GetFullPath(path);
Console.WriteLine(fullPath);
```

I wonder whether the problem is that your value just starts with a backslash, with no drive letter - if the current working directory isn't the drive you expect, that could cause a problem.

**Comment by hhblaze** [comment]
You were completely right, despite the fact that ENV.VAR was set on the level of the system and my local user, command
  Environment.GetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS");
returned null,
![image](https://user-images.githubusercontent.com/486781/32688136-a5eea9be-c6cb-11e7-9567-cc948c7c1a1f.png)

both cases have started to work after
Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", @"mypathtojson");
Though, after program restart this variable must be set again, because it answers for the env.variable of the current process.
