### ISSUE TITLE
Firestore: DocumentReference/CollectionReference are sealed classes

### ISSUE THREAD

**Issue by pauloevpr** [GoogleCloudPlatform/google-cloud-dotnet#1714]
Is there any special reason to make DocumentReference and CollectionReference sealed classes? It seems unreasonable to have such restriction. It makes very difficult to extend the functionalities of the API. 

For example, instead of calling `db.Collection("users").Document("id").Collection("purchases").Document("id")`, I could get rid of the magic strings and call something like `db.UsersCollection.UserDocument("id").PurchasesCollection.PurchaseDocument("id")`. That would be possible by creating custom collections and documents references by deriving DocumentReference/CollectionReference. 

Custom references would provide many useful features, such as:

- Declare your entire database structure in code
- Retrieve specific references without using magic strings
- Create reusable queries/procedures by using extension methods
- Improve the overall code readability, maintainability and scalability

**Comment by jskeet** [comment]
There's a big, big reason why these classes are sealed: they're immutable types. If you allow uncontrolled derivation from otherwise-immutable types, all the benefits go out the window. In addition to that, I'm a big fan of "Design for inheritance or prohibit it" - and this sort of "doing extra stuff" rather than "specializing how the existing functionality behaves" doesn't feel like a good use of inheritance to me.

I would suggest using composition instead of inheritance for this situation, so each of your custom classes contains a `CollectionReference` or a `DocumentReference` instead of inheriting from it - then you have the same code as your second line, but with benefits of:

- DocumentReference/CollectionReference are still guaranteed to be immutable (along with Query, FieldPath etc)
- You don't get a lot of *irrelevant* methods exposed: your types can be focused on your use case, with the escape hatch of getting at the contained reference if you really need to.

I'll bring your comments to the attention of the Firestore API team, but I suspect they'll agree with me on this one - especially given that the Java API also has final classes for `DocumentReference` and `CollectionReference`.

**Comment by pauloevpr** [comment]
So you basically haven't designed the code for inheritance. In this case, it is reasonable that the classes are sealed. 

However, I personally believe that the chosen design is not flexible, and it will require a lot more work for consumers needing customization. 

Consider that this API by definition lacks a lot of functionalities when comparing to the existent client APIs. That means developers will certainly have to deploy a bunch of extensions in order to achieve all the features they need. So having a flexible and extensible API seems like a necessity to me.

The idea of "specializing how the existing functionality behaves" is great. But because the code is rigid, developers would have to rely on Google to delivery these "specializing features". Wouldn't it be better if the community were able to develop such features on its own?

Yes, composition is always an option. Yes, it is possible to workaround restrictions. But the point is, the current design doesn't invite the community to help to extend the API.

**Comment by jskeet** [comment]
The point is that there's little in DocumentReference/CollectionReference *to* specialize - it's performed via the `FirestoreDb` class (or `WriteBatch`). Your use case doesn't specialize anything, and sounds like a *much* better candidate for composition than inheritance to me.

You've also ignored the aspect of immutability - in order to accommodate *your* use case, *everyone* has to take the hit that they can no longer rely on a `DocumentReference` value being a reference to an immutable data type, unless they have looked at all the code involved everywhere.

I don't believe that community involvement requires these immutable types to become unsealed. There are plenty of ways the community can get involved without that. Contributions to this library are welcome, although they'd need approval from the Firestore API team. Other libraries can spring up that use this library via composition - and I'd argue that doing so is *easier* to do in a robust way when there are more guarantees about `DocumentReference` and `CollectionReference`. If two third-party libraries both accept and return `DocumentReference` values, then in the current design they can do so with the knowledge that they're immutable - with your suggestion, any pairing of third-party libraries would have to be examined very carefully just in case one does something that would violate the assumptions of the other.

Again, the Firestore API team will be the ultimate arbiters of this, but my personal feeling is that the current design is the most suitable one.

**Comment by pauloevpr** [comment]
I think my previous comment did miss your point regarding the aspect of immutability. I apologize for that. Now that you brought reliability up, it seems very reasonable that these two classes are sealed.

My real concern is not regarding these two classes in particular, it is actually about making the API flexible so that the community can help to improve it by developing extension libraries. It seems you are already seriously taking this into consideration when developing the API. That is awesome!

This whole idea of making references more easy to access is not a particular use case of mine. I am actually wanting to develop a tool to help developers to materialize their Firestore database structure into code. The tool would basically auto generate helper classes and methods for references based on the provided database structure.

As far as I concern, this issue is completely resolved. Thank you very much for your time.

**Comment by jskeet** [comment]
Great! Closing now.
