### ISSUE TITLE
cloud FireStore error "Invalid property path" when key in a map has colon

### ISSUE THREAD

**Issue by Thaina** [GoogleCloudPlatform/google-cloud-dotnet#1805]
I have object look like this

```JSON
{
    "_id" : "uid0",
    "statistics" : {
        "Type:XXX:1:1" : { },
        "Type:XXX:2:2" : { },
        "Type:XXX:3:1" : { }
    }
}

{
    "_id" : "uid1",
    "statistics" : {
        "Type:XXX:1:2" : { },
        "Type:XXX:2:1" : { },
        "Type:XXX:3:1" : { }
    }
}

{
    "_id" : "uid2",
    "statistics" : {
        "Type:XXX:1:2" : { },
        "Type:XXX:2:2" : { },
        "Type:XXX:3:1" : { }
    }
}
```

I try to query it with orderby filter out only a documents with specific key

As example below I try to get all docs that has key `Type:XXX:2:2` in `statistics` so I write this code

```C#
FirestoreClient client;
RunQueryRequest runQueryRequest;


runQueryRequest.StructuredQuery	= new StructuredQuery();
runQueryRequest.StructuredQuery.From.Add(new StructuredQuery.Types.CollectionSelector(){ CollectionId = "players" });
runQueryRequest.StructuredQuery.OrderBy.Add(new StructuredQuery.Types.Order() { Direction = StructuredQuery.Types.Direction.Ascending,Field = new StructuredQuery.Types.FieldReference(){ FieldPath = "statistics.Type:XXX:2:2" } });
var fireStatistics	= awaitAsyncEnumerable.CreateEnumerable(() => client.RunQuery(runQueryRequest).ResponseStream).Where(resp => resp.Document != null).Select(resp => resp.Document.Fields.ToJSon()).ToArray();
```

I expect to get document that has id `uid0` and `uid2`

But it return error

```
"Grpc.Core.RpcException" : StatusCode=InvalidArgument, Detail= Invalid property path "statistics.Type:XXX:2:2"
```

Is it not possible or it was another kind of problem?

**Comment by jskeet** [comment]
Please give details about which API you're using - we don't have any context here. I'm *guessing* it's Datastore, but I'm not sure...

**Comment by Thaina** [comment]
@jskeet Sorry I was remove some wrong line when copy my code

**Comment by jskeet** [comment]
You should escape your property path as per https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/5c17c4f593782223943e227e209c32249f8eccab/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/FieldPath.cs#L109

... alternatively, just use the FieldPath class itself. We're not encouraging users to use the low-level API directly - the Google.Cloud.Firestore API is preferred in general.

**Comment by Thaina** [comment]
I see thank you very much

Still it not obvious when class `StructuredQuery.Types.FieldReference.FieldPath` itself is string not a `FieldPath` class. This google sdk somehow complicate about class that verify things like this

**Comment by jskeet** [comment]
I'm afraid I don't understand your last sentence, but the `FieldPath` class is in the `Google.Cloud.Firestore` API, rather than being a protobuf message. The whole point of the `Google.Cloud.Firestore` API is to avoid users having to worry about details like this. If you choose to use the low-level underlying API, there *will* be a lot more work to do.

**Comment by Thaina** [comment]
@jskeet Sorry for not being clear. I understand about `FieldPath` class. But the API for using FirestoreClient not using `FieldPath` class itself. Instead it use `StructuredQuery.Types.FieldReference` class and `StructuredQuery.Types.FieldReference` class also not use `FieldPath` class. But `FieldPath` property is just string

The reason why I don't use the `Google.Cloud.Firestore` higher level API because of the problem I was post a pull request #1796. I have my converter create `Dictionary<string,Value>` but the over higher level API cannot accept it

**Comment by jskeet** [comment]
Yes, so you use the `EncodedPath` property of `FieldPath`. You can still use that part of the higher level API even if you don't use anything else.

Alternatively, use a local fork of the higher level API with your PR in it for now - or write a temporary method to convert your `Dictionary<string, Value>` into an appropriate `Dictionary<string, Object>` so that you can use the higher level API, albeit slightly inefficiently. At the very least you could then see the queries issued.

I wouldn't suggest writing a lot of code in the lower level API just because of the problem you're trying to address with #1796.

**Comment by Thaina** [comment]
@jskeet Thanks for your suggestion but because I don't actually know about how the higher API wrapper really work that's why I don't want to hack it without official release

But the low level one is somehow work understandably. So in the meantime I would still use it

Also I test your guidance and it work. So thank you very much
