### ISSUE TITLE
Return content for GetSchemaTable() of Spanner DataReader

### ISSUE THREAD

**Issue by jerarl** [GoogleCloudPlatform/google-cloud-dotnet#1853]
We have a generic implementation for ADO.net that relies on reading the GetSchemaTable(). Currently it returns null but we need it to have some data for the ColumnName, Ordinal, and DataType with the addition of NumericPrecision, NumericScale and ColumnSize even if these 3 columns would just be empty.

**Comment by jskeet** [comment]
Assigned to Ben for comment on feasibility.

**Comment by benwulfe** [comment]
This is possible, but there are a few issues.

1. The first and most important issue is that once you return any somewhat viable table from GetSchemaTable( ), DbDataAdapter attempts to use that to create and manage datasets.  This is very easy to break if you do not have complete information to build a proper schema table (which spanner does not) -- so its much safer to return null and get default behavior.

2. There may be some limitations on when this data is accessible.  The best candidate for filling in this data is either from PopulateMetadata (see https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDataAdapter.cs#L240)  or from the raw DDL statement.  PopulateMetadata begins the stream read operation and if I recall correctly, there were some cases where you would want to call GetSchemaTable without actually executing the SQL query.  So these use cases would not be possible.  Using raw DDL would be prohibitively expensive because you'd need to build a parser to reverse engineer the DDL string.

So I guess to accommodate these two pitfalls, I would suggest a new method that does not imply GetSchemaTable semantics -- something like "GetReadMetadataTable" and provides roughly the same information using PopulateMetadata.  This isn't terribly difficult and can use the code in SpannerDataAdapter for inspiration.

Does this work?

**Comment by jskeet** [comment]
Creating a new method sounds like a good plan to me, but @jerarl presumably that wouldn't fit into your generic framework?

(I guess another possibility would be to make this an opt-in option somehow...)

**Comment by jerarl** [comment]
Yes, it wouldn't fit at all since it relies on the GetSchemaTable() method. How is it would work if we make this an opt-in option?

**Comment by jskeet** [comment]
Basically we could put options into the connection string that would tweak the behavior of some aspects, but I'm not 100% sure it's a good idea.

**Comment by jerarl** [comment]
I think its awesome and it should work in our case without affecting current users.

**Comment by benwulfe** [comment]
You can see an initial version of this method I left commented out here:

https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDataReader.cs#L336

If you use that, it most likely will break tests that use dbdataadapter.  Maybe there is a way to get dbdataadapter into a somewhat functional state with this code -- but if not, then I suppose the best we can do is guard the tests so they only run with the flag off.

**Comment by jskeet** [comment]
Just as an update, this hasn't fallen off my radar completely - but there are some other Spanner changes in motion that I want to get out first; I'll then look at what we do about this issue.

**Comment by jerarl** [comment]
Thanks, we're still waiting on when this will be implemented
