### ISSUE TITLE
Spanner DataReader return DBNull value instead of null

### ISSUE THREAD

**Issue by jerarl** [GoogleCloudPlatform/google-cloud-dotnet#1854]
When using the GetValues(object[] values), can we return DBNull value instead of null for null data?

**Comment by jskeet** [comment]
Ben, any reason not to do this? (I'm happy to implement the code - just checking whether it's appropriate.)

**Comment by benwulfe** [comment]
The only reason not to do this is the potential of breaking changes.

Note that the spanner 1.1 alpha release added support for setting DbNull  (see https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/d52a5788d4307d93a93af1620da149d846b9f3b9/apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDbType.ValueConversion.cs#L103)
which is back compatible (since it would just do the wrong thing before).

You can call "IsDbNull" and "true" will be returned for returned "null" values.
If this doesn't work for you, it is possible to return DbNull in place of null, but it might be best to do this protected with an option so we don't break existing users.

**Comment by jskeet** [comment]
Is it just `GetValues()` that has this problem, or do we return a null reference from all methods that should actually be returning `DBNull`?

**Comment by benwulfe** [comment]
I suspect you will want to change this line:

https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Spanner.Data/Google.Cloud.Spanner.Data/SpannerDbType.ValueConversion.cs#L44

to return DbNull if the DbNull type is assignable to the target type (and opt-in flag is set) and continue to fall thru to "return null" otherwise.
This should primarily affect the indexer from the datareader -- which GetValue calls into.

**Comment by jskeet** [comment]
Hmm. I'm thinking about whether we should just consider this to be a bug, and fix it to return `DBNull.Value` by default, with a compatibility opt-in switch. I can't see any ADO.NET documentation requiring it to to return `DBNull.Value` but I suspect more clients would expect that.

With a small number of current users, it may well be better to make a breaking change now than force all future users to opt in. Will need to consider this carefully. We'd obviously need clear release notes etc.

**Comment by jskeet** [comment]
Just as an update, this hasn't fallen off my radar completely - but there are some other Spanner changes in motion that I want to get out first; I'll then look at what we do about this issue.

**Comment by jerarl** [comment]
Thanks, we're still waiting on when this will be implemented

**Comment by jskeet** [comment]
Just implementing this now, there's a fly in the ointment: arrays. An individual spanner value can be an array, and we allow the clients to ask for (say) a `string[]`.

Proposal: only the top-level value is ever returned as `DbNull.Value`. Within arrays, the existing behaviour will be used instead (which is slightly unfortunate in terms of an `int[]` that contains a null Spanner value will have that converted to a 0, but I'm not sure there's a much better alternative).

**Comment by jskeet** [comment]
Ah - except repeated field elements can't be null, so this may not be a problem after all. I think we've got some integration tests which are testing for an impossible scenario.
