### ISSUE TITLE
Issue when using uploading AVRO using `BigQueryClient`

### ISSUE THREAD

**Issue by quoctruong** [GoogleCloudPlatform/google-cloud-dotnet#1866]
I was using the `UploadAvro` function like this:
```
AvroOptions = new UploadAvroOptions();
BigQueryJob bqj= Client.UploadAvro(InputObject, null, fileInput, AvroOptions);
bqj.PollUntilCompleted().ThrowOnAnyError();
```
And I get a request error with the message: "You should not provide a schema when loading self-describing binary formats. In the future this will fail with an error."

The same code snippet worked about 2 or 3 months ago. Is this because of some changes in the BigQuery API?

**Comment by jskeet** [comment]
Sounds like it may well be, yes. Will investigate on Monday.

**Comment by jskeet** [comment]
Thanks for spotting this. Our integration tests and snippets weren't sensitive enough to spot this non-fatal error.

Unfortunately it's hard to deprecate a parameter like this, and even adding overloads would be really tricky due to the nature of overload resolution. I'm creating a PR that simply ignores the provided schema in all cases, but doesn't change the signature. (Obviously the documentation will be changed.)

I'll then look at creating a patch release with that change.
