### ISSUE TITLE
Storage: terminology

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#188]
The Cloud Storage API universally uses the term insert to describe the action of adding an element.  The client uses the term ‘create’ to insert a bucket and the term ‘upload’ to insert an Object.

Is this confusing? Assigning to Chris for comment.

**Comment by csells** [comment]
Not to me, but perhaps something @ynr can ask customers about.

**Comment by YnR** [comment]
Good question. To make matters easier:

- **PowerShell cmdlets** use New-, which I'm told is an idiosyncrasy of PowerShell cmdlets. It also distinguishes between creating a new object (New-) and writing over an existing one (Write-).
- **gsutil** uses cp and rewrite

I'm reaching out to the Cloud Storage UX team in case they have guidance here.

**Comment by jskeet** [comment]
// cc @Capstan for comments from a Storage perspective.

**Comment by jskeet** [comment]
Decided this is correct for idiomatic C#.

**Comment by Capstan** [comment]
Sorry; didn't see this when it came by. We generally support CRUD+L, with some modifications for objects (Write instead of Create since it's not a stock `POST` single body necessarily, Read in addition to GetMetadata), and extra custom methods (Copy aka Clone, Rewrite, Compose). The model used for Google's discovery-based APIs assigned "insert" to Create, "get" to Read, "update" to Update, and "delete" to Delete, and that's what the JSON API uses.

**Comment by jskeet** [comment]
Right. I'm definitely happy with Create instead of Insert. Upload/Download feels like it makes sense for the data (as opposed to metadata). If you look at [the methods on StorageClient](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Storage.V1/api/Google.Storage.V1.StorageClient.html#methods) do any of those feel inappropriate to you?
