### ISSUE TITLE
[Firestore] CreateAsync() and AddAsync() don't support decimal type

### ISSUE THREAD

**Issue by mhh12121** [GoogleCloudPlatform/google-cloud-dotnet#1998]
I wanna upload an object to collection, but seems it doesn't work because this object contains a **decimal value**, which leads to an error ''Unable to convert value of type System.Decimal". 
Any solution about it?Thank you!

**Comment by jskeet** [comment]
Firestore doesn't have any type that maps cleanly to `decimal`. I haven't included a conversion for it, because I don't want to lose silently lose data.

If you're just after a floating point type and don't need it to be `decimal`, you can use `double` instead. If you need the exact decimal representation, you could store a `string` representation instead, but be aware that you won't be able to perform comparisons in queries that way.

**Comment by mhh12121** [comment]
Thank you for your replying! I think I need to consider another stupid way to convert it...
