### ISSUE TITLE
Add documentation explaining how to use custom credentials

### ISSUE THREAD

**Issue by chrisdunelm** [GoogleCloudPlatform/google-cloud-dotnet#2123]
Possibly add a sentence in the summary of `Create()` and `CreateAsync()` methods, with sample code in the remarks. For all libraries.

/cc @simonz130

**Comment by jskeet** [comment]
This is related to #1576.

**Comment by bryancrosby** [comment]
Additionally, is there any way to add custom scopes? For example, adding https://www.googleapis.com/auth/chat.bot to the scope creation? I couldn't find anything through the API at this point.

**Comment by jskeet** [comment]
@bryancrosby: Add custom scopes to what in particular? When you call `GoogleCredential.CreateScoped` you just pass in a set of strings. Those can be whatever strings you want. I'm not sure why you'd want to add arbitrary scopes to any of the APIs we're exposing at the moment, but I may be missing something.

**Comment by bryancrosby** [comment]
@jskeet Apologies for not being more clear. I noticed that the code works fine when the environment variable is defined, but for reading from a JSON file, other Google APIs have a `ReadFromJson` or `ReadFromStream` or some similar method defined.

I was trying to get a pub/sub resource with a service account to connect to a Hangouts chat bot using the pub/sub tutorial, but something isn't working. I can actually publish a message to a topic and have it received successfully when done through the Web UI as a test, but after following the tutorial for having a chat bot respond via pub/sub. I think there is a configuration problem somewhere related to the service account and my OU. That's a separate issue.

I just happened to notice that I have to set the environment variable vs having `CreateAsync` take a stream to the JSON file, so I thought I'd provide that feedback here.

**Comment by jskeet** [comment]
@bryancrosby: I'm not sure exactly what you mean by "other Google APIs" or what you're currently doing. Could you file a new issue that includes your code and details about what's not working?

Can I check first that you've read the docs at https://googlecloudplatform.github.io/google-cloud-dotnet/docs/faq.html#how-can-i-use-non-default-credentials-for-grpc-based-apis? They show how to specify scopes having created credentials from a file.

PubSub can be slightly different to other gRPC APIs due to the way it needs to create channels automatically, but that still may help. Beyond that, concrete details of the code and the error would make it a lot easier to help you - but ideally in a separate issue.
