### ISSUE TITLE
How to end the conversation from webhook.

### ISSUE THREAD

**Issue by xspatil** [GoogleCloudPlatform/google-cloud-dotnet#2133]
Could anybody help me to end the conversation from C# webhook. dialogflow.v2 version

**Comment by jskeet** [comment]
I'm afraid the maintainers of this repository are not experts on the particular APIs, only the client libraries. Do you have examples from other languages? If so, we may be able to help translate the code. Otherwise, I'd suggest asking on https://productforums.google.com/forum/#!forum/dialogflow or Stack Overflow.

**Comment by xspatil** [comment]
response.data.google.expectUserResponse=false...how can we set this in C#.

**Comment by jskeet** [comment]
Closing due to lack of response, but I suspect the details in #2134 would help you.
