### ISSUE TITLE
No docs published for Cloud IAM

### ISSUE THREAD

**Issue by danoscarmike** [GoogleCloudPlatform/google-cloud-dotnet#2195]
Cloud IAM package on Nuget here: https://www.nuget.org/packages/Google.Cloud.Iam.V1/

Expected to find API reference docs here: https://googlecloudplatform.github.io/google-cloud-dotnet/docs/index.html but the API is not listed.

**Comment by jskeet** [comment]
Currently the IAM package is effectively present as a common dependency for other packages. The documentation is included with those packages, e.g. in the [PubSub API documentation](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.PubSub.V1/api/Google.Cloud.PubSub.V1.html)

We generate protobuf and gRPC client code, but we don't generate the higher-level code which makes it more directly usable, as we don't intend the client to be used directly. We could revisit that decision, but for the moment I think it's reasonable not to have separate IAM documentation - just to include it within the APIs where it will be used.

**Comment by danoscarmike** [comment]
SGTM. Thanks for clarifying Jon.

**Comment by jan-amtote** [comment]
Hello! We're currently looking into migrating from `Google.Apis.Iam.v1` as suggested. We're currently using `IamService.Projects.ServiceAccounts.Keys` to list/create/delete [`projects.serviceAccounts`](https://cloud.google.com/iam/docs/reference/rest/v1/projects.serviceAccounts). Unfortunately, I can't seem to find a documentation on how to do this with the new `Google.Cloud` packages (I'm currently digging into the source code hoping to find it). Is there a way to do this with the new packages? Thank you!

It would also be nice to have the example C# code (at least for `project.serviceAccounts`) to be updated to use the new packages: e.g. https://cloud.google.com/iam/docs/reference/rest/v1/projects.serviceAccounts/list

**Comment by jskeet** [comment]
@jan-amtote: Typically the Google.Cloud.Iam.V1 package is used via specific APIs which expose methods to affect the IAM for those APIs. This package does not currently have an equivalent of `project.serviceAccounts/list`.

The `Google.Cloud.Iam.Credentials.V1` package ([docs](https://googleapis.dev/dotnet/Google.Cloud.Iam.Credentials.V1/latest/index.html)) is where I'd expect to find that call, but it doesn't exist at the moment. For now, I'd suggest using [Google.Apis.Iam.v1](https://www.nuget.org/packages/Google.Apis.Iam.v1/) package which *does* look like it lets you do what you want. It's one of our "old style" libraries, but it should work.

**Comment by jan-amtote** [comment]
@jskeet Thank you for confirming! Yes, the `Google.Cloud.Iam.Credentials.V1` is working but we try to migrate to the latest/suggested package/version if possible. Should I create a new issue to track adding a C# method to hit `project.serviceAccounts.keys`? (Note: I edited my comment above after realizing that it's actually the `.keys` endpoint we're hitting instead of just `project.serviceAccounts`, but it looks like both are missing in the new cloud packages)

**Comment by jskeet** [comment]
> Should I create a new issue to track adding a C# method to hit project.serviceAccounts.keys

No, because we automatically generate all the methods exposed via gRPC. We wouldn't be adding it to either of the existing APIs.

Looking at [this proto](https://github.com/googleapis/googleapis/blob/master/google/iam/admin/v1/iam.proto), it looks like basically we'd want a Google.Cloud.Iam.Admin.V1 package. I'll talk internally about whether we want that.

**Comment by jan-amtote** [comment]
Alright! Thank you for looking into this! We'll keep using `Google.Apis.Iam.V1` as suggested. 🍻
