### ISSUE TITLE
Add support for Xamarin Android and ARM platform

### ISSUE THREAD

**Issue by andreabonassi** [GoogleCloudPlatform/google-cloud-dotnet#2219]
Good morning,
Have you already plan to support Xamarin Android (ARM) platform also?
Do you have any alternative to this library that I can start using right away?
Thanks.

**Comment by jskeet** [comment]
No, we don't support Xamarin or Unity at the moment, and doing so is challenging due to the gRPC native code dependency. In theory it should be possible to cross-compile the native library, but we haven't tried it - and I expect there may well be other challenges.

While we would like to expand our platform support in the future, we're not actively working on it right now.

**Comment by Thaina** [comment]
Just a reminder that GRPC for both xamarin and unity is now exist as experimental

https://github.com/grpc/grpc/tree/master/src/csharp/experimental

**Comment by jskeet** [comment]
@Thaina: Thanks for the reminder, but there's still more work to do beyond *just* gRPC - there's authentication, and making sure we can test reliably as well. We're still keen on doing this, but please don't expect it in these libraries any time soon.
