### ISSUE TITLE
URL from webhook

### ISSUE THREAD

**Issue by xspatil** [GoogleCloudPlatform/google-cloud-dotnet#2231]
Can anybody help me sending the anchor tag from fullfillment text property from Webhook response object.

**Comment by jskeet** [comment]
Could you give more details please, ideally with an example of the code you've got so far? Note that the regular contributors for this repository have relatively little experience with specific APIs - we're more about supporting the C# libraries themselves.

One thing to note is that if you're using `Google.Cloud.Dialogflow.V2`, you should call `ToString()` on your response proto and return that string, rather than letting Json.NET serialize the proto for you. (Likewise on the parsing side - accept a string and parse it as JSON with the protobuf parser, rather than expecting Json.NET to do it.)

**Comment by jskeet** [comment]
Closing based on lack of further information.
