### ISSUE TITLE
FirestoreChangeListener usage

### ISSUE THREAD

**Issue by DenSmoke** [GoogleCloudPlatform/google-cloud-dotnet#2250]
I am testing C# SDK for Firestore and wrote some code:
```C#
private FirestoreChangeListener usersListener;
public void Startlisten(Reciever reciever)
{
      CollectionReference collection = db.Collection("Users");
      usersListener = collection.Listen(snapshot =>
      {
                foreach (DocumentChange change in snapshot.Changes)
                    reciever($"{change.Document.Reference.Id}: ChangeType={change.ChangeType}; OldIndex={change.OldIndex}; NewIndex={change.NewIndex})\n");
      });
}
```

Output of code:
`EsGo79j9FHR9zJz9TAnm: ChangeType=Added; OldIndex=; NewIndex=0)`
`MjIlGRtFNfbD8upA0ykK: ChangeType=Added; OldIndex=; NewIndex=1)`
`OHeik9ENhd1N8Wu1c0DB: ChangeType=Added; OldIndex=; NewIndex=2)`
`QqBPeio6MNtorFIfjFzX: ChangeType=Added; OldIndex=; NewIndex=3)`

Is it normal that FirestoreChangeListener shows all `ChangeType=Added` changes since creation of Database every time when Query.Listen creates it?

**Comment by jskeet** [comment]
I suspect that's expected, in terms of the document being added to the query results... But I'll check on Monday with the Firestore team.

**Comment by DenSmoke** [comment]
I think two options can be there:
1. Listener gives all types of changes at start;
2. Listener doesn't give changes which were made before listening started.

**Comment by jskeet** [comment]
Sorry for this not getting traction before - I was away at conferences all week and this slipped past me. I'll email the team now.

**Comment by jskeet** [comment]
I've heard back from the team, and this is the expected behavior. It's effectively syncing *state* rather than *changes*... so the initial state is "everything in the collection when you start".

If you want to only see changes, you could have a commit timestamp in your document, and write a query to say "Only show me items with a value later than this timestamp" and pass in a timestamp of the current time.

Given that this is the expected behavior, are you happy for me to close this issue?

**Comment by DenSmoke** [comment]
Yes, the issue is solved, you can close it. Thanks
