### ISSUE TITLE
firestore not allow the c# code datetime other than UTC

### ISSUE THREAD

**Issue by anirugu** [GoogleCloudPlatform/google-cloud-dotnet#2251]
Currently, I need to convert the date to UTC before entering it in Firestore.

for example I write code like this  
`record.post_date = DateTime.SpecifyKind(record.post_date.GetDateTime(), DateTimeKind.Utc);`

it's a MySQL DateTime, if it's have unspecified, it's told to set to UTC, I didn't tried with local.  it must take all kind of DateTime where it's Local, Unspecified or UTC.

it's not working, I write code like this for every column to make it work.

**Comment by jskeet** [comment]
No, I won't be changing this. A Firestore timestamp *is* UTC, and it's up to you to make sure you provide the right UTC value. A `DateTime` with a `Kind` that isn't UTC could mean any number of different things, and I wouldn't want the client library to make an implicit - and quite possibly wrong - choice about that.

You may be able to change how you access MySQL to make it provide you with UTC values, but I'm not going to change the Firestore library in a way that could silently lead to incorrect data being stored.

**Comment by anirugu** [comment]
I am reading the values from MySQL using dapper. I am using Wordpress database, without Zero DateTime and with Zero DateTime both cases are not working. 

What could be a better option here, I mean I simply want to put my date to the firestore. This means I need to write some code for every table which have DateTime column

**Comment by jskeet** [comment]
> What could be a better option here

Fixing your data. I do sympathize, but the problem isn't at the "inserting data into Firestore" stage, it's at the "fetching data from MySQL" stage. If your database values are meant to represent UTC timestamps, then what you should end up with in your .NET code is `DateTime` values with a `Kind` of `Utc`.

If you really can't get Dapper/MySQL to provide you with that, then I suggest you either just write the per-table code, or write some code that uses reflection to do so in a general way so that you can just call that on any table data.

I will *not* compromise the integrity of the Firestore library by allowing you to insert ambiguous data.

**Comment by anirugu** [comment]
Thanks for the reply, I will check and let you know if setting UTC Timezone In MySQL make my code work without writing any code for datetime.
