### ISSUE TITLE
Please add implicit conversion from Tuple of strings to fieldpath

### ISSUE THREAD

**Issue by Thaina** [GoogleCloudPlatform/google-cloud-dotnet#2301]
Just for convenient

```C#
public implicit operator FieldPath((string,string) paths) => new FieldPath(paths.Item1,paths.Item2);
// up to tuple of 8
```

So we could use

```C#
var stream = firestoreDB.collections("users").WhereEqualTo(("profile","type"),"Tester").StramAsync();
```

**Comment by jskeet** [comment]
While this is clearly possible and I'll consider it, my current inclination is not to do it:

- Implicit conversions need to be *really* carefully considered. They make all kinds of API design trickier.
- We'd need to add a dependency on `System.ValueTuple` - definitely doable, but I think a dependency really needs to have significant value to be worth including.
- We'd need to add several conversions, based on the arity - how far would you expect us to go? Would a depth of 4 be enough? More?
- I tend to avoid using `ValueTuple` in public APIs in general. I regard it as a type which is convenient as an internal detail, but with no fixed semantics I don't think it's a good fit for public APIs
- I also tend to think of `ValueTuple` as more of a bag of values rather than a *sequence* of values, which is how they'd be used here.

For field paths used in queries, I'd personally suggest using static readonly fields (or properties) instead. This would avoid constructing the same `FieldPath` object again and again, and if you use it in multiple places you're protected against typos, and if you change the structure of your documents you'd only have a single place to change.

**Comment by jskeet** [comment]
You can't create conversions from interfaces - the language doesn't allow it. (I'm not sure what your `With` method is even attempting to do at the moment.)

I'd be much happier to add a `FieldPath With(string next)` method to `FieldPath` though. Then if your `fieldA` and `fieldB` variables were of type `FieldPath`, that would work.

**Comment by jskeet** [comment]
(In fact we already have that method as `Append` at the moment, but it's internal - so it would just be a matter of renaming it and making it public.)

**Comment by Thaina** [comment]
@jskeet What I want here is a way throw some string into firestore API that need fieldpath without even mentioning about fieldpath anywhere in the code

I forgot about implicit conversion rule. So another way might be having overload method for every place using `FieldPath` to also have API for `IEnumerable<string>`

**Comment by jskeet** [comment]
I definitely don't want to add overloads everywhere. Instead, I suggest you add a static `FP` method like this to your project:

```
public static class FieldPathUtilities
{
    public static FieldPath FP(params string[] segments) => new FieldPath(segments);
}
```

You can then use `using static FieldPathUtilities;` to import that method anywhere you'll need it. You can then just write:

```csharp
transaction.Update(userDoc, FP(fieldA, "time"), ServerValue.TimeStamp);
```

(etc). You can name it however you want, do whatever you want with it.

If you really want `fieldA.With("time")` to work, you could always write your own extension method on `string` to do that. That way you can get the behaviour you want without affecting other users or introducing the complexity of huge numbers of extra overloads.

**Comment by Thaina** [comment]
> I definitely don't want to add overloads everywhere

That's why I was proposing that it should be just implicit conversion from `Tuple<string..>` and `FieldPath` at the beginning

**Comment by jskeet** [comment]
I've explained why I don't want to add implicit conversions either though. I really think the static method route is the best way to give you a more convenient syntax for the moment. It doesn't stop us from *maybe* adding conversions later on, but it's much harder to remove things later than to add them.

**Comment by jskeet** [comment]
Closing this as I believe the workaround is very usable, without imposing the expanded-API issues on other users.
