### ISSUE TITLE
Using UrlSigner with ComputeCredential and IamService is painfully slow

### ISSUE THREAD

**Issue by sebastianbk** [GoogleCloudPlatform/google-cloud-dotnet#2411]
Hi,

First of all, I would like to thank the entire .NET team at Google Cloud working on making the whole development experience so much nicer within the GCP ecosystem. I really appreciate your huge efforts and I hope you will stay committed to supporting .NET in GCP for many years to come.

Almost all of the features related to deploying .NET applications in App Engine have been really pleasant. However, I have recently run into an issue that is bugging me quite a bit so, maybe if I am lucky, you will be able to help me out.

I have built an ASP.NET Core 2.1 application, which I have deployed using the `gcloud` command-line tools to App Engine. Everything worked great after ironing out a few minor issues. Though, after doing a bit of testing, I ran into the problem of signing GCS blob URLs as described in #2316 and #2338.

I implemented @jskeet's suggested solution described [here](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Storage.V1/index.html#signed-urls) under the _Signing URLs without a service account credential file_ section. I assigned the role _Service Account Token Creator_ to the default App Engine service account and, at first sight, the solution seemed to work well.

However, after a bit of testing (using Stackdriver Trace, which is truly amazing), I realized that IAM-based solution was terribly slow. In comparison to instantiating a `UrlSigner` with the `FromServiceAccountPath` method (using the private key of service account purposely created for the task with the _Storage Admin_ role), the signing of URLs using the `IamService` class is more than 50 times slower on average. I did a small sample where I signed 10 blob URLs, which I repeated 10 times, and the `FromServiceAccountPath` solution executed this job in less than 100 ms on average while the `IamService`-based solution took around 5 seconds.

I really do not know how to optimize this, other than deploying the private key of my other service account with my application, which I really do not want to do. Do you know of any tips or tricks that can help me improve the performance?

Thank you very much!

**Comment by jskeet** [comment]
That's to be expected: the IAM approach is making a network call and the service account approach isn't.

Fundamentally, you've decided not to keep sensitive information locally - which helps meet various requirements, but then means that in order to perform operations that *require* sensitive information, you need to make a network call. It's a trade-off.

If you don't mind the service account file being present on the machine eventually, but don't want to deploy it, you could keep that somewhere centrally (possibly further encrypted, e.g. with KMS) and fetch it on start-up. That way the network impact of not deploying the sensitive material would be limited to start-up. If you never want the service account file to be present locally, I'm not sure that there's a better way than your current approach.

**Comment by jskeet** [comment]
@sebastianbk: Any more feedback on this? I don't anticipate there being any more changes in this repo for this, so I'd like to close the issue if possible.

**Comment by jskeet** [comment]
Closing for now; this can be reopened in the future if there is more feedback or specific requests.
