### ISSUE TITLE
Deserializing empty object to attributed class

### ISSUE THREAD

**Issue by DenSmoke** [GoogleCloudPlatform/google-cloud-dotnet#2432]
Deserializing converts null object in array field of Firestore document to requested object type with same fields containing default values (null or zero).
After 
```C#
foreach (var change in snapshot.Changes)
{
    //...
    var report = change.Document.ConvertTo<Report>();
    //...
}
```
this
![image](https://user-images.githubusercontent.com/16131575/44333303-1aa6c280-a477-11e8-8b5d-e28e626e981d.png)
becomes this
![image](https://user-images.githubusercontent.com/16131575/44333371-41fd8f80-a477-11e8-90a2-ab7196711e02.png)
Parts of my classes:
```C#
[FirestoreData]
public class Report
{
    //...
    [FirestoreProperty("usedDetails")]
    public List<Detail> UsedDetails { get; set; }
    //...
}
[FirestoreData]
public class Detail
{
    [FirestoreProperty("name")]
    public string Name { get; set; }
    [FirestoreProperty("quantity")]
    public int Count { get; set; }
    [FirestoreProperty("price")]
    public double Price { get; set; }
}
```
What's wrong?
It really doesn't affect my project, I discovered this by accident.

**Comment by jskeet** [comment]
You say it's a "null object" - are you sure it's not an *empty* object? Those are very different. This is the exact behavior I'd expect if your array is populated with empty objects. I don't know offhand whether a Firestore array *can* contain null entries, but if it can, I'd only expect null references at that point.

Are you able to provide the content of your document in its JSON representation, by any chance? That would help clarify things.

(Alternatively, if you have code that creates such a document, I'd be happy to use that to investigate further.)

**Comment by DenSmoke** [comment]
Yes, object is really empty according to debugger (Firebase console doesn't shows it clearly):
![image](https://user-images.githubusercontent.com/16131575/44335793-2cd82f00-a47e-11e8-968b-3d0d8809cdaa.png)

I created this document (on first screenshot) manually via console

**Comment by jskeet** [comment]
Right - in that case, it's behaving exactly as I'd expect it to. Each object in the array is being deserialized in the same way as if you presented an empty value to the individual deserializer: create an instance of the object, and then set "all" the fields (of which there are none).

To get null values, you'd need to have `nullValue` values instead of `mapValue` values.

Does that make sense?

**Comment by DenSmoke** [comment]
It seemed to me strange that the read operation changes source object

**Comment by jskeet** [comment]
I'm not sure what you mean - it was an empty object before, and reading it you still get an effectively empty object. I'd be more concerned about turning an empty object into null.

**Comment by jskeet** [comment]
> Also I thought that after I got a DocumentSnapshot I don't perform any remote operations i.e. serialization and conversion occurs offline

It does. It's not clear what you think is happening here - or what you'd expect to happen.

It's just like deserializing `"{}"` with Json.NET - you end up with an object with no properties explicitly set, so they have their default values.

Perhaps I've misunderstood what you're seeing - could you provide a short but complete example in code rather than the screenshots? (It's not clear to me what you're looking at or at what point.) Maybe there *is* a real problem here and I've just misunderstood what you're seeing...

**Comment by DenSmoke** [comment]
> It's just like deserializing "{}" with Json.NET - you end up with an object with no properties explicitly set, so they have their default values.

I understood now why empty objects becomes this object. This situation is impossible when using Dictionary to store objects so this behaviour was not clear for me.
So there is no problem there, it is just Json.NET serializarion/deserialization feature.

My document in Firestore was updating because of trigger which updates document when serialized object differes from stored json

**Comment by jskeet** [comment]
Just to be clear - Json.NET itself isn't involved here. I was only giving an example of a similar situation. 

There's no difference between "An object which has been created and no properties have been set" and "An object which has been created and its properties set to their default values."

It sounds like we're mostly on the same page now though :)
