### ISSUE TITLE
Overloads for flattened ByteString method args

### ISSUE THREAD

**Issue by bdhess** [GoogleCloudPlatform/google-cloud-dotnet#2441]
See also GoogleCloudPlatform/google-cloud-java#3590

It would be nice if flattened RPC calls had overloads that accepted standard .NET types (i.e. a .NET `byte[]`) instead of always requiring a protobuf `ByteString`.  The latter ends up leaking an implementation detail to callers.

As an example, in Cloud KMS we currently have:
```
string textRaw = "The quick brown fox jumps over the lazy dog!";
EncryptResponse encRes = kms.Encrypt(keyPath, ByteString.CopyFromUtf8(textRaw));
```

It would be nice if the final line could be
```
EncryptResponse encRes = kms.Encrypt(keyPath, Encoding.UTF8.GetBytes(textRaw));
```

**Comment by jskeet** [comment]
This one I'd rather not do. We'd end up with an explosion of overloads, particularly with the string-formatted path values as well. There are many different types you might want to create a `ByteString` from:

- A `byte[]`
- A `Span<byte>`
- A `ReadOnlySpan<byte>`
- A `string`
- A `Stream`

In a method with multiple parameters, you may well have different source types. And how would we choose whether to do this with the overloads accepting strings or the ones accepting resource names, when that feature is implemented? It feels cleaner to keep to a smaller number of overloads and specify how to create the `ByteString` in each case.

@chrisdunelm Do you agree?

**Comment by jskeet** [comment]
Note that we expose the protocol buffer types *all over the place* - any response objects returned, the overloads accepting request objects, any resources returned are protobuf messages etc. It's not like we're trying to hide protobuf away, wrapping it so that we can exchange it for a different transport later on etc. (We *do* do that in the Firestore API - Google.Cloud.Firestore doesn't expose anything from Google.Cloud.Firestore.V1Beta1 except the FirestoreClient, IIRC. That's an escape hatch that most users won't need to use.) But in general, and certainly for the generated clients, we don't try to "wrap" opaquely.

**Comment by bdhess** [comment]
You've outlined a number of drawbacks I hadn't considered, and ultimately convinced me that this is a bad idea.  I'm going to withdraw this request. :)
