### ISSUE TITLE
Problem with google cloud speech client on UWP application

### ISSUE THREAD

**Issue by 20092738** [GoogleCloudPlatform/google-cloud-dotnet#2455]
When attempting install google cloud speech client library to UWP application, I got the error message from nuget console as below:

>  Install-Package : Package Google.Cloud.Speech.V1 1.0.1 is not compatible with uap10.0.16299 (UAP,Version=v10.0.16299). Package 
> Google.Cloud.Speech.V1 1.0.1 supports:
>   - net45 (.NETFramework,Version=v4.5)
>   - netstandard1.5 (.NETStandard,Version=v1.5)

**Comment by jskeet** [comment]
Yes, I'm afraid our client libraries don't currently support UWP.

**Comment by 20092738** [comment]
Thank you @jskeet , shall your client libraries support UWP application in the future ?
Currently, is there any way to use google cloud speech service on UWP application ?

**Comment by jskeet** [comment]
We would *like* to support UWP, but it's further down the priority list than Unity and probably Xamarin support.

You could *try* using the Google.Apis.Speech.v1 API, which talks via HTTP1/REST instead of HTTP2/gPRC, but:

- That library still doesn't officially support UWP, and in particular the authentication aspects may well cause problems. (You'd be able to use a service account, but distributing that is not ideal to say the least.)
- That library won't support any streaming operations.

I'm going to close this issue as we're not expecting to take any direct action on it in this repo - you can still add comments, of course. We'll update the [supported platforms documentation](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/guides/platforms.html) if and when UWP is supported.
