### ISSUE TITLE
Paging with StorageClient

### ISSUE THREAD

**Issue by yetanotherchris** [GoogleCloudPlatform/google-cloud-dotnet#2511]
Is it possible to page with the `StorageClient` in the current version of the .NET Api?

I've looked at the source and can see the nextPageToken is being set by an internal `PageManager`, for one big page, but there doesn't seem to be a manual way of:

1. Fetch 100 items, page 1
2. Fetch 200 items, page 2
3. so on..

**Comment by jskeet** [comment]
I'm not *quite* sure what you're trying to achieve, but it sounds like you're after the `ReadPage` method, which will read the next page of data up to a certain page size, performing multiple requests if necessary to ensure you get the exact page token for your page boundary. There's an example here:

https://googlecloudplatform.github.io/google-cloud-dotnet/docs/guides/page-streaming.html#display-the-next-fixed-sized-page-of-results

Is that what you're after? There's no way of going *straight* to a specific page by number, without a page token, if that's what you were asking.

**Comment by yetanotherchris** [comment]
Hi Jon, I'm after the equivalent of AWS's `ContinuationToken` - the docs link you gave seems to be it, but I can't see how you specify it for `StorageClient`

**Comment by jskeet** [comment]
Just to check, do you mean you don't know how to *get* at the page token, or how to specify it? Because you'd *get* it from the `Page<Object>` (returned by `ReadPage`),  but you're right - there's nowhere to specify it in `ListObjects` or `ListBuckets`, which definitely surprises me!

I'd normally expect this as a separate parameter in the calls, but introducing that would be a breaking change at this point, so I'll put it into `ListObjectsOptions` and `ListBucketsOptions`.

We have the same issue in the `BigQuery` API :(

I'll try to get onto this next week. Thanks for pointing it out!

**Comment by yetanotherchris** [comment]
How to set it for subsequent requests

**Comment by jskeet** [comment]
This was released as Google.Cloud.Storage.V1 version 2.3.0-beta01. If you get a chance to try it out, it would be great to hear whether it works for you.

**Comment by yetanotherchris** [comment]
Looks good to me, the previous failing test on the project I'm working on pass now 👍
