### ISSUE TITLE
Several API Reference links in ReadMe don't work

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-dotnet#267]
Most (if not all) the links in the ReadMe file don't link to the API Reference anymore.

For instance: 

https://googlecloudplatform.github.io/google-cloud-dotnet
http://googlecloudplatform.github.io/google-cloud-dotnet/api/Google.Bigquery.V2.html
....

All don't work.

**EXPECTED RESULT**
The first link should direct users to the landing page:
https://googlecloudplatform.github.io/google-cloud-dotnet/0.1.0/index.html

The API specific links should direct the user to the right API Reference location:
https://googlecloudplatform.github.io/google-cloud-dotnet/0.1.0/docfx/index.html#google-bigquery-v2-alpha

(or perhaps here instead too for now since users already see the example on GitHub: https://googlecloudplatform.github.io/google-cloud-dotnet/0.1.0/docfx/api/Google.Bigquery.V2.BigqueryClient.html)

**Comment by jskeet** [comment]
Where did you get the second link? The first is a problem with the redirect due to the name change. It's not clear to me exactly what's wrong there, as the index.html file is correct.

The second isn't expected to work since we reworked the documentation.

I'll look into the first problem again tomorrow - it may be that github is doing a redirect unhelpfully itself.

**Comment by jskeet** [comment]
First link now works, btw. I've now found the links you refer to in the readme (sorry for not spotting the context before) and will fix them.
