### ISSUE TITLE
Update "Google APIs" to "Google Cloud Client Library"

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-dotnet#269]
**CURRENT SETUP**
Navigating to https://googlecloudplatform.github.io/google-cloud-dotnet/0.1.0/index.html shows as the first line the following text: "Google APIs for .NET provide..."

**EXPECTED RESULT**
The first sentence should say "Google Cloud Client Library for .NET ..."

In other words, it should mimic (and perhaps be the same) was what these others languages say:

https://googlecloudplatform.github.io/gcloud-node/
https://googlecloudplatform.github.io/gcloud-ruby/
https://googlecloudplatform.github.io/gcloud-php/

**Comment by jskeet** [comment]
"Google Cloud Client Library for .NET ..." makes it sound like there's a single client library. There isn't, which is why it *doesn't* mimic the other platforms (where there is a single central package). This was a deliberate change. I'm happy to change it to something else, but it'll need to be accurate.

**Comment by jskeet** [comment]
First link works now, but you'll need to clear your cache.
Second link is no longer meant to work, so I'm closing this issue.
