### ISSUE TITLE
Upsert() returns null pointers.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#308]
The documentation for Upsert() says it returns a list of keys.  It returns a list, but the keys are all null.  In code:

```
            KeyFactory keyFactory = _db.CreateKeyFactory("People");
            Entity from = new Entity()
            {
                Key = keyFactory.CreateKey("from"),
                ["balance"] = 100
            };
            Entity to = new Entity()
            {
                Key = keyFactory.CreateKey("to"),
                ["balance"] = 0
            };
            var keys = _db.Upsert(from, to);
            // keys is {null, null}.
            return new[] { from.Key, to.Key };
```

**Comment by jskeet** [comment]
Okay, I see the problem - the RPC only returns keys for *inserted* entities.

Options here:

- Update the documentation to match reality, and keep it so that only inserted entities have their keys reflected in the return value
- Update the implementation to always return *all* keys, whether they were inserted or updated.

What's your preference here? And what would you like `Update` to do? (We already have the keys there, so is it worth returning them at all?)

**Comment by SurferJeffAtGoogle** [comment]
I prefer updating the documentation.  I can imagine a situation where I want to know which keys were inserted vs. updated.

**Comment by jskeet** [comment]
Sounds good to me. Are you happy for me to remove the return value of Update, given that it will always be a collection of null references?

**Comment by jskeet** [comment]
Reopening to give @SurferJeffAtGoogle the chance to say whether this is now appropriate or not.

**Comment by jskeet** [comment]
Ping @SurferJeffAtGoogle - have you had a chance to use the beta02 build yet?

**Comment by jskeet** [comment]
I believe this is now done.
