### ISSUE TITLE
What's the status of the currently published NuGet packages?

### ISSUE THREAD

**Issue by markvincze** [GoogleCloudPlatform/google-cloud-dotnet#454]
I'm a bit confused by the NuGet packages currently published. I tried to google, but couldn't find information about this.

As far as I understand, this repository is the current version of the .NET client libraries. I'd like to use Google Datastore, and I can see in the `project.json` that it supports `netstandard1.5`.
On the other hand, if I get the release from NuGet (https://www.nuget.org/packages/Google.Datastore.V1/1.0.0-beta02), it only supports the full .NET Framework. Is this just because it hasn't been pushed to NuGet in a while?

The other thing is that I can see another package, [Google.Apis.Datastore.v1](https://www.nuget.org/packages/Google.Apis.Datastore.v1/), which indeed supports `netstandard1.3`. Is that an old SDK, which will be deprecated?

So which one is the recommended package to start using Google Datastore in .NET **Core** today?
Is there maybe a blogpost or documentation which gives information about this topic?

**Comment by jskeet** [comment]
Yes, we only started depending on gRPC 1.0.0-pre1 very recently, and it's that that enables us to target netstandard1.5. We haven't done a release since then. We have a bunch more work to land before our next release, but yes, it's coming at some point. If this is a major blocker for you, I can look into doing another beta earlier than we expected to.

Google.Apis.Datastore.v1 is a stable library which uses the REST API for Datastore. Good news: it's stable. Bad news: it's considerably less pleasant to use than `Google.Datastore.V1`.

If you're happy to use prerelease software, I'd recommend Google.Datastore.V1. If you need something which is already GA, use the REST API.

There's no blog post about this, as any such post would almost immediately be out of date... for example, the commit to include netstandard1.5 support only landed 6 days ago...

**Comment by markvincze** [comment]
@jskeet Thanks for the quick answer! Now it's clear.

Prerelease is not a problem, so I guess I'll just use the source code directly until a new release is dropped on Nuget.
