### ISSUE TITLE
Rename BigqueryQueryJob

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/google-cloud-dotnet#456]
It's a job from BigQuery which we know represents a query. In that sense, BigqueryQueryJob is perfect. In every other sense, it's awful. Fixing this should be trivial in terms of keystrokes, once the right name has been found...

**Comment by jskeet** [comment]
Posisbly `BigqueryResults`, like it used to be? That's what it's typically *used* for, although it represents a query job really...

**Comment by roji** [comment]
I agree that `BigQueryResults` isn't ideal, since it conveys the idea that results are already available - whereas the job may not have completed yet.

One idea that comes to mind, is to replace the BigQuery prefix with BQ across the entire library (so BQQueryJob, etc.). This would remove the offensive `QueryQuery`, and would also reduce name lengths across the entire codebase. However, that might be a too-big a change, affecting other GCP client libraries as well?

**Comment by jskeet** [comment]
It wouldn't affect anything else, but it would feel a little odd to me. I don't think BigQuery is ever abbreviated like that. It's worth considering, but I'd like to try to think of some other options too.

**Comment by jskeet** [comment]
(BigQueryResults was agreed offline - partly as you can now access the data without explicitly polling for completion.)
