### ISSUE TITLE
No way to rename/move a storage object.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#479]
I tried this code.  It had no effect:

```
        private void MoveObject(string bucketName, string sourceObjectName,
            string destObjectName)
        {
            var storage = StorageClient.Create();
            var storageObject = storage.GetObject(bucketName, sourceObjectName);
            storageObject.Acl = storageObject.Acl ?? new List<ObjectAccessControl>();
            storageObject.Name = destObjectName;
            storage.UpdateObject(storageObject);
            _out.WriteLine($"Moved {sourceObjectName} to {destObjectName}.");
        }
```

**Comment by jskeet** [comment]
Right - I wouldn't expect it to, knowing the underlying API just a little bit. RESTful APIs generally don't support the notion of "move" as an operation, as far as I'm aware.

I believe Move has to be implemented via Copy+Delete, but Copy should be very quick within the same bucket. (The CopyObject method doesn't need to pull the content down to the client and back, for example.)

**Comment by SurferJeffAtGoogle** [comment]
I'll try the copy+delete, work-around, but I'd like to leave this bug open.  Given the API, I think other users will attempt this same method of moving files.  And, having an atomic move operation on a storage system is _really_ useful.

**Comment by jskeet** [comment]
I'm sure it would be really useful, but it's not exposed by the API, as far as I'm aware! We could potentially expose methods which perform Copy+Delete, but it won't be atomic. I'm also not sure how much benefit it gives... we can try it and see.

We can probably *detect* that the user has tried to do the update approach, by checking `storageObject.Name` against other properties (I think there's duplication there) - and then give a helpful error message. Will have a look and send a PR as a "what do you think?" solution to this.

**Comment by Capstan** [comment]
It is not currently an API intrinsic. You can copy, and conditionally delete, but if the delete fails, you may not be able to back out the copy, etc. Also, if the destination is not a compatible location or identical storage class, the copy isn't a simple metadata operation and requires moving bytes around.

**Comment by jskeet** [comment]
@Capstan: Ah, I wasn't aware of the "conditional delete" part - that would certainly help. Will look into it further - thanks for the hint :)

**Comment by SurferJeffAtGoogle** [comment]
Trying to infer the user's intention is tough to get right.  I'd rather avoid that.

**Comment by Capstan** [comment]
The condition is limited, but the model you can use is `storage.objects.get` and record `generation` and `metageneration`, and use those as `storage.objects.copy` as conditional source arguments, and record the copy's `generation` and `metageneration`. If that fails, you're done. If it succeeds, you do a `storage.objects.delete` as conditional arguments. If that fails, you're now somewhat stuck, since you've already successfully committed the copy and anything that triggers (e.g., bucket with versioning on it and new archive versions, object change notifications), so you can't really universally undo it. The closest thing you can do is try a conditional delete of the copy with the copy's `generation` and `metageneration` and hope for the best.

**Comment by jskeet** [comment]
Closing as not something we want to do in the libraries - but we'd like a detailed sample going into how client code would do it, and what considerations they'd need to think about. @SurferJeffAtGoogle do you need me to raise an issue in your repo about that?
