### ISSUE TITLE
StorageClient.GetBucket() returns bad info after updating bucket.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#533]
```
            var storage = StorageClient.Create();            
            var bucket = storage.GetBucket(bucketName);
```
observed bucket.Acl.Count = 1

```
            if (null == bucket.Acl)
            {
                bucket.Acl = new List<BucketAccessControl>();
            }
            bucket.Acl.Add(new BucketAccessControl()
            {
                Bucket = bucketName,
                Entity = $"user-{userEmail}",
                Role = "OWNER",
            });
            var updatedBucket = storage.UpdateBucket(bucket, new UpdateBucketOptions()
            {
                // Avoid race conditions.
                IfMetagenerationMatch = bucket.Metageneration,
            });
```

observed updatedBucket.Acl.Count = 2

```
            var storage = StorageClient.Create();
            var bucket = storage.GetBucket(bucketName);
```

observed bucket.Acl.Count = 0

What happened?

**Comment by jskeet** [comment]
If you don't specify that you want all the details, you don't get the ACLs. If you use:

```csharp
var bucket = storage.GetBucket(bucketName, new GetBucketOptions { Projection = Projection.Full });
```

then you'll get all the ACLs.

**Comment by SurferJeffAtGoogle** [comment]
Is it a bug that the code behaves differently despite the request being identical?  It definitely feels like a bug.

**Comment by jskeet** [comment]
Ah, I hadn't spotted that the first call to `GetBucket` returned an ACL. Will investigate.

**Comment by jskeet** [comment]
I can't reproduce this at all - I end up with the `Acl` property being null every time. Code:

```csharp
var client = StorageClient.Create();
var name = "bug-" + Guid.NewGuid().ToString();
var bucket1 = client.CreateBucket("jonskeet-uberproject", name);
Console.WriteLine($"Create: {bucket1.Acl?.Count ?? -1}");
var bucket2 = client.GetBucket(name);
Console.WriteLine($"Get: {bucket2.Acl?.Count ?? -1}");
bucket2.Acl = new List<BucketAccessControl>
{
    new BucketAccessControl { Bucket = name, Entity = $"user-{email}", Role = "OWNER" },
    new BucketAccessControl { Bucket = name, Entity = $"allUsers", Role = "READER" }
};
var bucket3 = client.UpdateBucket(bucket2, new UpdateBucketOptions { IfMetagenerationMatch = bucket2.Metageneration });
Console.WriteLine($"Update: {bucket3.Acl?.Count ?? -1}");
var bucket4 = client.GetBucket(name);
Console.WriteLine($"Get: {bucket4.Acl?.Count ?? -1}");
client.DeleteBucket(bucket4);
```

Output:

```text
Create: -1
Get: -1
Update: -1
Get: -1
```

I'm not sure how you managed to get any ACLs to start with...

**Comment by chrsmith** [comment]
When using the Apiary client libraries, you need to specify the `Projection` field on the request to get all of the ACL information. Otherwise it is (for some odd reason) not included in the response. We do this in the PowerShell bits [here](https://github.com/GoogleCloudPlatform/google-cloud-powershell/blob/4e31c416474794910537ddbe19b6d9faacea5ac5/Google.PowerShell/Storage/GcsBucketLogging.cs#L42).

See:
https://cloud.google.com/storage/docs/json_api/v1/buckets/get

    projection	string	Set of properties to return. Defaults to noAcl. 

    Acceptable values are:
    "full": Include all properties.
    "noAcl": Omit owner, acl and defaultObjectAcl properties.

**Comment by SurferJeffAtGoogle** [comment]
To reproduce, run the tests in this project:
https://github.com/SurferJeffAtGoogle/csharp-docs-samples/tree/storageAcl/storage/api-veneer

**Comment by jskeet** [comment]
Running those tests gives me output of:

```csharp
QuickStart.exe create
Created aumkmixussctfywqhvik.
QuickStart.exe add-owner aumkmixussctfywqhvik 230835935096-8io28ro0tvbbv612p5k6nstlaucmhnrq@developer.gserviceaccount.com
QuickStart.exe print-acl aumkmixussctfywqhvik
Google.Apis.Requests.RequestError
Forbidden [403]
Errors [
	Message[Forbidden] Location[ - ] Reason[forbidden] Domain[global]
]

QuickStart.exe delete aumkmixussctfywqhvik
Deleted aumkmixussctfywqhvik.
```

But debugging into the tests shows me `bucket.Acl` being null in the first part, where you say you observed it being non-null. Basically, all the code is behaving as I expect it to, not returning the ACLs unless you ask for them... the only thing that surprises me is you saying you observed `bucket.Acl` being non-null. Are you still able to reproduce that? If you remove the `if (null == bucket.Acl) { ... }` statement, I'd expect you to see a `NullReferenceException`, and indeed that's what happens when I try it.

**Comment by SurferJeffAtGoogle** [comment]
I can't reproduce it with the latest version of the libraries.
