### ISSUE TITLE
RateLimiter stress test is failing occasionally

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-dotnet#610]
The RateLimiter stress test is failing sometimes:
https://ci.appveyor.com/project/GoogleCloudPlatform/google-cloud-dotnet/build/1.0.463-appveyor

The failure seems to only be one extra trace.

I can't seem to repo the issue with the current test on linux or windows.

**Comment by jskeet** [comment]
(I've seen it two or three times on AppVeyor, but only AppVeyor.)

**Comment by evildour** [comment]
I also saw this locally when I was testing the initial stress test problems (before the task yields were added). I had increased the timeout to 30.1 seconds and forced the process to use a single core and I was almost always getting 31 traces instead of 30. So maybe even with the yields the original thread is not getting control again for another second. Maybe check for elapsed time before and after the delay and use the floor of the elapsed seconds as an upper bound on the allowed trace count.

**Comment by iantalarico** [comment]
@evildour I think that may be the solution.  When I increase the tasks and time limit the total run time goes well over the delay but the floor of the elapsed time seems to always be the correct count.

**Comment by evildour** [comment]
Ok cool. You may want to allow for it to be off by one though (one fewer than you expect) because if the elapsed time is close to 3000 milliseconds, you'll expect 3 traces, but the 3rd might not have gone through.

**Comment by jskeet** [comment]
It's now failing more than occasionally (on AppVeyor), possibly related to the introduction of coverage. I'll skip it for now, but add some more diagnostics and investigate further.

**Comment by jskeet** [comment]
Sample output with some more diagnostics:

```text
Starting at 11:57:48.750
Incrementing at 11:57:50.772
Incrementing at 11:57:52.771
Finished at 11:58:02.763
```

Notice how there's a 10 second gap. I wonder whether the VM gets suspended periodically, which would definitely affect things. Adding more diagnostics...

**Comment by jskeet** [comment]
When we start the threads, they're completely tight-looping, which means it takes quite a long time even to start all the threads.

Options (not mutually exclusive):

- Create a semaphore so that we can wait for all the threads to start, then work out the end time, then release the sempahore
- Just pause for a second inside the thread, so all the threads can be started
- Create fewer threads
- Sleep(1) inside the loop, effectively like Thread.Yield
- Change the timing so that we get the threads going, reset the counter and time it from that point

@iantalarico Any thoughts?

**Comment by iantalarico** [comment]
I think the semaphore would be the next best thing to try if the sleep doesn't work.  Thanks for looking at this Jon!
