### ISSUE TITLE
Issuing "gcloud auth login" wasn't enough to get the SDK working

### ISSUE THREAD

**Issue by markvincze** [GoogleCloudPlatform/google-cloud-dotnet#676]
I tried to use the SDK in a .NET Core application on Ubuntu 16.10 to access the Datastore. Based on the documentation, before running my application I've run `gcloud auth login` in the terminal to make sure I'm authenticated.

However, I received the following exception:

```
Unhandled Exception: System.TypeInitializationException: The type initializer for '<StartupCode$myapp>.$Startup' threw an exception. ---> System.InvalidOperationException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(ServiceEndpoint endpoint)
```

In order to fix the problem, I had to execute the command `gcloud auth application-default login`, afterwards my application started working.
Is this incorrect in the documentation, or is there something wrong on my machine?

**Comment by jskeet** [comment]
Hmm... I'd expect it to work, but it's possibly that `gcloud auth login` no longer does what's needed. (I know it's an area which has been in flux.) Using `gcloud auth application-default login` should definitely be fine - it was in beta last I checked, which is why it isn't recommended in the docs.

When I'm back at work in the new year, I'll dive into this more deeply and update the docs. Thanks for reporting - and please let me know any other feedback you have on the Datastore API.

**Comment by jskeet** [comment]
Yup, it looks like application-default is no longer in beta, and the usage of gcloud auth login has changed.

Updating docs...
