### ISSUE TITLE
[Pub/Sub] Publishing API Feedback

### ISSUE THREAD

**Issue by Singh400** [GoogleCloudPlatform/google-cloud-dotnet#849]
Hi,

I have been playing around with the Pub/Sub (`1.0.0-beta07`) API for the past week or so. I appreciate that the API is still evolving and explicitly marked as beta. But I have some feedback, specifically regarding publishing a message. My current usage looks like this:-

	public void Publish<T>(T message) where T : IGoogleMessage
	{
		var topic = CreateTopicIfNeeded<T>();

		_publisher.Publish(topic, new[]
		{
			new PubsubMessage
			{
				Data = ByteString.CopyFromUtf8(JsonConvert.SerializeObject(message))
			}
		});
	}

But in an ideal world it would look more like this:-

	public void Publish<T>(T message) where T : IGoogleMessage
	{
		var topic = CreateTopicIfNeeded<T>();

		var pubsubMessage = new PubsubMessage
		{
			Data = JsonConvert.SerializeObject(message)
		};

		_publisher.Publish(topic, pubsubMessage);
	}

There are a couple things that I wanted to raise:-

1. As a consumer of the API, I do not need to know that `Google.Protobuf` is used under the hood by the API. It adds noise to my code and (IMO) leaks out what is being used by the Pub/Sub API. I would like to see the `Protobuf` pushed down away from consumer usage. Ideally, I should never know that `Protobuf` is being used.
2. When publishing the message, I understand why the API accepts an `IEnumerable`. But in all of our use cases we publish message immediately as single operations. I would like to see the API support this.

Thanks for reading :)

Many thanks,
Singh

**Comment by jskeet** [comment]
Firstly, thanks for the feedback and using the API.

To address your individual points:

Firstly, hiding protobuf isn't going to happen. In order to maintain complete fidelity with the API,  there has to be an object model that behaves exactly the same way as protobuf. Manually writing an object model would be a maintenance headache, and generating another object model just to act in the same way as one we already have seems worse than pointless. It would add a great deal of risk of subtle bugs. 

I would say that you should be *aware* that protocol buffers are being used, but in *most* cases it shouldn't need to be particularly visible in your code. It's more visible here than normal due to `ByteString` - but we can minimize that *and* solve your "publish single message" issue simply by adding two extension methods:

```csharp
public static ByteString ToByteString(this string text) => ByteString.CopyFromUtf8(text);

public static void Publish(this PublisherClient client, TopicName topic, PubsubMessage message, CallSettings callSettings = null) =>
    client.Publish(topic, new[] { message }, callSettings);
```

Your code would then look very *close* to your ideal:

```csharp
public void Publish<T>(T message) where T : IGoogleMessage
{
    var topic = CreateTopicIfNeeded<T>();
    var pubsubMessage = new PubsubMessage
    {
        Data = JsonConvert.SerializeObject(message).ToByteString();
    };
    _publisher.Publish(topic, pubsubMessage);
}
```

You could even have an extension method to convert `IGoogleMessage` to `PubsubMessage` if you wanted.

The current API is entirely autogenerated. It's possible that we'll add an abstraction layer over the top in the future, but I don't think we'll be expanding the autogenerated layer.

**Comment by jskeet** [comment]
I'm going to close this as "won't fix" because we're not intending to make any changes, but please don't read that as meaning that we don't value feedback. Keep the ideas coming - particularly if you use APIs with more hand-written code such as Datastore.
