### ISSUE TITLE
Google.Cloud.Speech and proxy

### ISSUE THREAD

**Issue by vds7** [GoogleCloudPlatform/google-cloud-dotnet#852]
I tried the recognize sample but I run in some proxy issues, are there any way to use proxies with Google.Cloud.Speech?

**Comment by jskeet** [comment]
I would expect it to work fine, but it *is* using HTTP 2.0 (because that's what gRPC uses). It might be worth looking through the gRPC documentation at http://grpc.io and asking on their [github repo](github.com/grpc/grpc) if that doesn't help. It would also be a good idea to try another API, e.g. Cloud Vision, just to see if you have the same problem with that. (I'd be surprised if this were Speech-only.)

**Comment by jskeet** [comment]
Hi @vds7, have you been able to try any of the steps I've suggested here?

**Comment by vds7** [comment]
Hi, I tried the cloud Vision sample and I got similar result.
I also tried the go lang speech sample  with the same result.
I looked at grpc but I'm still not able to set a proxy.

**Comment by jskeet** [comment]
Okay, so this definitely sounds like a connectivity issue. I would suggest opening a bug on the gRPC github repo, as the users there are much more likely to be able to help you. Please ensure that you include relevant networking details such as any proxies involved.

**Comment by jskeet** [comment]
Closing this issue as it's not directly related to the code in this repo.
