### ISSUE TITLE
Machine Learning API Library

### ISSUE THREAD

**Issue by sguergachi** [GoogleCloudPlatform/google-cloud-dotnet#904]
An API library to access the Cloud ML APIs would be really helpful.

**Comment by jskeet** [comment]
To clarify, are you looking to build your own machine learning code, or use Google's existing ML services? We have libraries for the Vision, Speech and Natural Language ML APIs, and I'll be working on Translation next week. If you're thinking about TensorFlow though, that's a different matter.

**Comment by sguergachi** [comment]
Essentially a Nuget that programatically lets me interact with this JSON API: https://cloud.google.com/ml-engine/reference/rest/

I already have a TensorFlow model hosted on CloudML, but interacting with the JSON API is requiring a lot more work.

**Comment by jskeet** [comment]
Right, so the ML Engine API.

There's already https://www.nuget.org/packages/Google.Apis.CloudMachineLearning.v1beta1/
- I'm not sure why the v1 (rather than v1beta1) package isn't on Nuget for it, as it's [been generated](https://github.com/google/google-api-dotnet-client/tree/master/Src/Generated/Google.Apis.CloudMachineLearningEngine.v1) - you could always fetch that code yourself at the moment.

That's the "old" code generator which won't be as usable as a hand-written library or the more modern code generator, but it should still work.

I'll close this issue for the moment, as hopefully this it what you were looking for.

**Comment by jskeet** [comment]
My mistake - the v1 package is here; the package was renamed slightly:

https://www.nuget.org/packages/Google.Apis.CloudMachineLearningEngine.v1/

**Comment by sguergachi** [comment]
Would be nice to add that to the README

**Comment by jskeet** [comment]
I will see if I can get something added to the Cloud Machine Learning Engine readme - we're not going to list every API which is supported from a *different* codebase to the READMe for *this* repo.
