### ISSUE TITLE
Dependency Issues with Google Cloud Storage V1 on Visual Studio 2015

### ISSUE THREAD

**Issue by jinkerflicks** [GoogleCloudPlatform/google-cloud-dotnet#928]
Hi,
We got through building our library which uses Google Cloud Storage V1 (pre release version) to connect to our Google Cloud Storage.
While going through the development, we realized that Google.Api.Gax.dll (1.21.0.0) is still looking for Google.Apis.Auth.PlatformServices.dll (1.20.0.0), even though the NuGet package manager downloads the 1.21.0.0 version of Google.Apis.Auth.PlatformServices.dll
This is forcing us to use binding redirects on our API's as a workaround since we don't have access to Google.Apis.Auth.PlatformServices.dll.
While this works ok for us in the short run, we would like to stay away from Binding Redirects on our API's.
Can you please suggest us a solution to this, or, provide us with an ETA of when the reference issue would be fixed on Google.Cloud.Storage.V1
Thank you in advance.
![image](https://cloud.githubusercontent.com/assets/26634369/24266225/78aaa0d0-0fdc-11e7-9641-d4c711c2fc9a.png)

**Comment by jskeet** [comment]
Fundamentally I suspect you need to make sure that binding redirects aren't a problem for you - because I expect they *will* be needed in the future.

For example, suppose we release Google.Cloud.Storage.V1 v1.0.0 with a dependency on Google.Apis.Storage.v1 v1.22, and Google.Api.Gax also uses Google.Apis.* v1.22. That's great temporarily - but at some point we may well need to use some feature in a later version of Google.Apis.Storage.v1 that will depend on Google.Apis.* v1.23. With everything following SemVer, that should be fine - all the Gax could should work perfectly well with Google.Apis.* v1.23, but obviously assembly binding redirects are required to satisfy the runtime.

We would *not* want to have to re-release Google.Api.Gax every time a library needed some new feature from another library which Google.Api.Gax depends on... this is precisely what assembly binding redirects are there for.

I'd expect this to all be transparent, with Visual Studio or the dotnet SDK simply doing the right thing for you - but expecting not to need binding redirects at all is unrealistic, IMO.

**Comment by jskeet** [comment]
Closing for now, as I don't think there's any way to avoid this. Please feel free to add more comments of course.

**Comment by jinkerflicks** [comment]
Thanks for providing valuable input, we will continue using the binding redirects.
